# -*- coding: utf-8 -*-
"""langgraph_hitl_loan_approval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dd99eoNg8Pw9FuZggxwF_VhfLEEgZ6-B

# 🏦 LangGraph HITL — Loan Approval Workflow

## Architecture
```
START
  │
  ▼
┌─────────┐      ┌──────────┐      ┌──────────┐
│ Planner │─────▶│ Executor │─────▶│ Verifier │
└─────────┘      └──────────┘      └────┬─────┘
                      ▲                  │ conditional
                      │   loop back      │
                      └──── rejected ────┤
                                         │ approved
                                         ▼
                              ┌──────────────────┐
                              │  route_by_risk   │  (conditional edge)
                              └────────┬─────────┘
                                       │
                         ┌─────────────┴──────────────┐
                         │                            │
                         ▼                            ▼
                  ┌─────────────┐           ┌──────────────────┐
                  │ auto_process│           │  human_review    │
                  │  (low risk) │           │ ⏸ interrupt()    │
                  └──────┬──────┘           │ (high value/risk)│
                         │                  └────────┬─────────┘
                         │                           │
                         └──────────┬────────────────┘
                                    ▼
                                   END
```

## Key Nodes
| Node | Role |
|------|------|
| **Planner** | LLM generates AI recommendation + risk score for each loan |
| **Executor** | Routes loans: auto-process (low risk) vs. human review queue |
| **Verifier** | LLM-as-judge scores quality; loops back if below threshold |
| **human_review** | `interrupt()` pause — waits for underwriter decision via `Command(resume=...)` |
| **auto_process** | Directly stamps low-risk loans APPROVED |

## 🔑 API Key Required
> **You need a Groq API key.**  
> Get one free at: https://console.groq.com/keys  
> Paste it into the cell marked `GROQ_API_KEY = "YOUR_GROQ_API_KEY_HERE"` below.

No other API keys are needed.

---
## Step 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install langgraph langchain-core langchain-groq langchain-community duckduckgo-search python-dotenv

"""---
## Step 2 — Set Your Groq API Key


"""

# ============================================================
#  🔑  PASTE YOUR GROQ API KEY HERE — this is the ONLY key
#      required to run this entire notebook.
# ============================================================
GROQ_API_KEY = "Enter Your API key"

import os
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print("✅ Groq API key set.")

"""---
## Step 3 — Imports & Shared Types
"""

import os
import json
from enum import Enum
from dataclasses import dataclass
from typing import TypedDict, List, Optional, Annotated
import operator

from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_community.tools import DuckDuckGoSearchRun

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command

print("✅ All imports successful.")

"""---
## Step 4 — Domain Types

These mirror the original `LoanRequest` dataclass and `ReviewDecision` enum exactly,
but are now embedded inside the LangGraph `LoanState` TypedDict so the graph can
carry and update them across nodes.
"""

# ── ReviewDecision enum (unchanged from original) ──────────────────────────────
class ReviewDecision(Enum):
    APPROVE  = "approve"
    REJECT   = "reject"
    ESCALATE = "escalate"


# ── LoanRequest dataclass (unchanged from original) ────────────────────────────
@dataclass
class LoanRequest:
    application_id:   str
    loan_amount:      float
    applicant_summary: str
    ai_recommendation: str
    risk_score:       float
    review_required:  bool                     = False
    human_decision:   Optional[ReviewDecision] = None
    reviewer_id:      Optional[str]            = None
    review_notes:     Optional[str]            = None


# ── LoanState — the single shared state object for the LangGraph graph ─────────
# This replaces the ad-hoc class variables from the original HITLWorkflow and
# makes all fields first-class graph state that every node can read/write.
class LoanState(TypedDict):
    # -- Planner outputs --
    goal:              str           # high-level goal string for the planner LLM
    tasks:             List[str]     # sub-tasks generated by the planner

    # -- Executor / HITL outputs --
    loans:             List[dict]    # raw input loan dicts
    processed_loans:   List[dict]    # loans enriched with routing decision
    review_queue:      List[dict]    # loans that need human review
    auto_queue:        List[dict]    # loans cleared for auto-processing

    # -- Verifier outputs --
    results:           List[str]     # per-task execution results
    critique:          str           # verifier feedback on last run
    approved:          bool          # verifier approval flag
    iterations:        int           # safety counter — force-approve after 3

    # -- Final decisions --
    final_decisions:   List[dict]    # combined auto + human decisions


# ── Thresholds (same as original HITLWorkflow constants) ───────────────────────
HIGH_VALUE_THRESHOLD = 1_000_000   # INR 10 lakhs
HIGH_RISK_SCORE      = 0.7

print("✅ Domain types defined.")

"""---
## Step 5 — LLM & Tools Setup
"""

pip install -U ddgs

# LLM — same model as the reference notebook
llm = ChatGroq(
    temperature=0,
    model_name="llama-3.1-8b-instant",
    groq_api_key=GROQ_API_KEY
)

# Web search tool (used by executor for research tasks)
search = DuckDuckGoSearchRun()

print("✅ LLM (llama-3.1-8b-instant via Groq) ready.")
print("✅ DuckDuckGo search tool ready.")

"""---
## Step 6 — Node Definitions

### Node 1: Planner
Mirrors the `planner` node from the reference notebook — breaks the goal into ≤ 5 tasks.
"""

def planner(state: LoanState) -> LoanState:
    """
    Planner node — identical pattern to the reference notebook.
    Breaks the high-level goal into concrete actionable tasks (JSON array).
    """
    system = """You are a planning agent for a loan approval workflow.
Break the goal into at most 5 concrete, actionable tasks.
Respond ONLY with a valid JSON array of strings. No preamble, no markdown."""

    messages = [
        SystemMessage(content=system),
        HumanMessage(content=f"Goal: {state['goal']}")
    ]
    response = llm.invoke(messages).content.strip()

    try:
        clean = response.replace("```json", "").replace("```", "").strip()
        tasks = json.loads(clean)
    except json.JSONDecodeError:
        tasks = [response]  # fallback: treat entire response as one task

    print(f"\n[Planner] Generated {len(tasks)} tasks:")
    for i, t in enumerate(tasks):
        print(f"  {i+1}. {t}")

    return {**state, "tasks": tasks}

print("✅ planner node defined.")

"""### Node 2: Executor

Extends the reference notebook's `executor` with HITL routing logic from `HITLWorkflow.route()`.
For each loan it:
1. Calls the LLM (optionally with web-search context) to execute research tasks
2. Routes each loan using the same thresholds as the original `HITLWorkflow`
   — amount ≥ INR 10L **or** risk ≥ 0.7 → `review_queue`; otherwise → `auto_queue`
"""

def executor(state: LoanState) -> LoanState:
    """
    Executor node — mirrors the reference notebook's executor.
    Additionally performs HITL routing (replicates HITLWorkflow.route()).
    """
    results      = []
    review_queue = []
    auto_queue   = []
    critique_ctx = ""

    if state["critique"]:
        critique_ctx = (
            f"\n\nYour previous attempt was rejected. "
            f"Previous critique: {state['critique']}"
        )

    # ── Execute each planned task via LLM + optional web search ────────────────
    for task in state["tasks"]:
        system = (
            f"You are an execution agent for a loan approval process. "
            f"Complete the task thoroughly. {critique_ctx}"
        )

        search_ctx = ""
        try:
            search_result = search.run(task[:100])
            search_ctx = f"\n\nWeb search context:\n{search_result[:800]}"
        except Exception:
            pass

        messages = [
            SystemMessage(content=system),
            HumanMessage(content=f"Task: {task}{search_ctx}")
        ]
        result = llm.invoke(messages).content
        results.append(result)
        print(f"\n[Executor] Task: {task[:60]}...\n  Result (truncated): {result[:200]}")

    # ── HITL Routing — replicates HITLWorkflow.route() ──────────────────────────
    print("\n" + "─" * 65)
    print("🔄 LANGGRAPH-STYLE HITL ROUTING")
    print("─" * 65)

    for loan in state["loans"]:
        needs_review = (
            loan["loan_amount"] >= HIGH_VALUE_THRESHOLD
            or loan["risk_score"] >= HIGH_RISK_SCORE
        )
        loan["review_required"] = needs_review

        if needs_review:
            route_label = "human_review"
            icon = "🔄"
            review_queue.append(loan)
        else:
            route_label = "auto_process"
            icon = "⚡"
            auto_queue.append(loan)

        print(
            f"{icon} [{route_label.upper():14}] "
            f"[{loan['application_id']}] "
            f"INR {loan['loan_amount']:>12,.0f} | "
            f"Risk: {loan['risk_score']:.2f}"
        )

    print(f"\n📋 REVIEW QUEUE: {len(review_queue)} pending")
    for r in review_queue:
        print(
            f"   [{r['application_id']}] "
            f"INR {r['loan_amount']:,.0f} | "
            f"Risk: {r['risk_score']:.2f} | "
            f"{r['applicant_summary'][:50]}"
        )

    return {
        **state,
        "results":      results,
        "review_queue": review_queue,
        "auto_queue":   auto_queue,
        "iterations":   state["iterations"] + 1,
    }

print("✅ executor node defined.")

"""### Node 3: Verifier

LLM-as-judge — identical pattern to the reference notebook.
Scores the executor's output on completeness, accuracy, and clarity.
Returns `approved=True` to continue to HITL routing, or `approved=False` to loop back.
"""

def verifier(state: LoanState) -> LoanState:
    """
    Verifier node — LLM-as-judge, mirrors the reference notebook's verifier.
    Force-approves after 3 iterations to prevent infinite loops.
    """
    # Safety net — force approve after 3 iterations (same as reference notebook)
    if state["iterations"] >= 3:
        print("[Verifier] Max iterations reached — force approving.")
        return {**state, "approved": True}

    combined_results = "\n\n".join(
        f"Task {i+1}: {t}\nResult: {r}"
        for i, (t, r) in enumerate(zip(state["tasks"], state["results"]))
    )

    system = """You are a quality verifier for a loan approval workflow.
Evaluate the execution results against the original goal using this rubric:
- Completeness: Does it fully address the goal? (0-0.4)
- Accuracy:     Is the information correct and specific? (0-0.3)
- Clarity:      Is it well-structured and clear? (0-0.3)
Sum the scores for a total between 0.0 and 1.0.
Respond ONLY as JSON:
{"score": 0.85, "completeness_score": 0.35, "accuracy_score": 0.25, "clarity_score": 0.25, "approved": true, "critique": "..."}
No preamble, no markdown."""

    messages = [
        SystemMessage(content=system),
        HumanMessage(
            content=f"Original goal: {state['goal']}\n\nResults:\n{combined_results}"
        )
    ]
    raw = llm.invoke(messages).content.strip()

    try:
        clean   = raw.replace("```json", "").replace("```", "").strip()
        verdict = json.loads(clean)
        approved = verdict.get("approved", False)
        critique = verdict.get("critique", "")
        score    = verdict.get("score", 0)
    except Exception:
        approved, critique, score = False, raw, 0

    print(f"\n[Verifier] Score: {score:.2f} | Approved: {approved}")
    if not approved:
        print(f"  Critique: {critique}")

    return {**state, "approved": approved, "critique": critique}


def route_after_verify(state: LoanState) -> str:
    """
    Conditional edge after verifier — same logic as reference notebook.
    'end_routing' leads to the HITL routing nodes; 'executor' loops back.
    """
    return "end_routing" if state["approved"] else "executor"

print("✅ verifier node defined.")

"""### Node 4: auto_process
### Node 5: human_review  ← the real LangGraph `interrupt()` gate

`human_review` uses LangGraph's native `interrupt()` to **pause the graph** and
wait for a real reviewer. The graph resumes when you call `app.invoke(Command(resume=...))`.  
This replaces `HITLWorkflow.human_review_node()` with a proper checkpointed pause.
"""

def auto_process(state: LoanState) -> LoanState:
    """
    Auto-process node — handles low-risk / low-value loans without human review.
    Mirrors the 'auto_process' branch of the original HITLWorkflow.route().
    """
    final_decisions = list(state.get("final_decisions", []))

    print("\n⚡ AUTO-PROCESSING low-risk loans...")
    for loan in state["auto_queue"]:
        decision = {
            **loan,
            "human_decision": ReviewDecision.APPROVE.value,
            "reviewer_id":    "AUTO_SYSTEM",
            "review_notes":   "Auto-approved: below risk and value thresholds",
        }
        final_decisions.append(decision)
        print(
            f"  ✅ [{loan['application_id']}] "
            f"INR {loan['loan_amount']:,.0f} — AUTO-APPROVED"
        )

    return {**state, "final_decisions": final_decisions}


def human_review(state: LoanState) -> LoanState:
    """
    Human-review node — the true LangGraph HITL interrupt gate.

    Uses interrupt() to PAUSE the graph and surface the review queue
    to the caller.  The graph only continues when you call:

        app.invoke(
            Command(resume={"decisions": [...]}),
            config=thread_config
        )

    Each decision dict must have:
        {
          "application_id": "APP100302",
          "decision":       "approve" | "reject" | "escalate",
          "reviewer_id":    "UNDERWRITER_001",
          "notes":          "Manual review complete"
        }
    """
    print("\n" + "═" * 65)
    print("⏸  HITL INTERRUPT — Pausing for human review")
    print(f"   {len(state['review_queue'])} loan(s) require underwriter attention:")
    for loan in state["review_queue"]:
        print(
            f"   • [{loan['application_id']}] "
            f"INR {loan['loan_amount']:,.0f} | "
            f"Risk: {loan['risk_score']:.2f} | "
            f"AI: {loan['ai_recommendation']}"
        )
    print("═" * 65)

    # ── interrupt() pauses graph execution here ────────────────────────────────
    # The dict passed to interrupt() is surfaced to the caller as the
    # interrupt value — it tells the human reviewer what needs deciding.
    human_input = interrupt({
        "message":      "Loans require underwriter decision.",
        "review_queue": state["review_queue"],
    })

    # ── Graph resumes here after Command(resume=...) ────────────────────────────
    # human_input is whatever was passed in Command(resume=...)
    decisions      = human_input.get("decisions", [])
    final_decisions = list(state.get("final_decisions", []))

    print("\n👤 Human review decisions received:")
    for loan in state["review_queue"]:
        # Find matching decision from the resume payload
        match = next(
            (d for d in decisions if d["application_id"] == loan["application_id"]),
            None
        )
        if match:
            decision = {
                **loan,
                "human_decision": match["decision"],
                "reviewer_id":    match.get("reviewer_id", "UNKNOWN"),
                "review_notes":   match.get("notes", ""),
            }
            final_decisions.append(decision)
            print(
                f"   [{loan['application_id']}] → "
                f"{match['decision'].upper()} "
                f"by {match.get('reviewer_id', 'UNKNOWN')}"
            )
        else:
            # No decision provided — escalate by default
            decision = {
                **loan,
                "human_decision": ReviewDecision.ESCALATE.value,
                "reviewer_id":    "SYSTEM",
                "review_notes":   "No decision received — escalated",
            }
            final_decisions.append(decision)
            print(f"   [{loan['application_id']}] → ESCALATED (no decision received)")

    return {**state, "final_decisions": final_decisions}

print("✅ auto_process and human_review nodes defined.")

"""### Conditional Edge: route_by_risk

After the verifier approves, this edge decides whether any loans need human review.  
If the review queue is empty → `auto_process` only.  
If there are loans waiting → `human_review` first (auto-process loans are handled inside `auto_process`).
"""

def route_by_risk(state: LoanState) -> str:
    """
    Conditional edge after verifier approves.
    Routes to 'human_review' if any loans need manual inspection,
    otherwise goes straight to 'auto_process'.
    """
    if state.get("review_queue"):
        return "human_review"
    return "auto_process"

print("✅ route_by_risk conditional edge defined.")

"""---
## Step 7 — Build & Compile the Graph

The graph uses `MemorySaver` as its checkpointer — required for `interrupt()` to work.
Without a checkpointer, LangGraph cannot persist state across the pause/resume cycle.
"""

# ── Build the graph ─────────────────────────────────────────────────────────────
graph = StateGraph(LoanState)

# Add all 5 nodes
graph.add_node("planner",      planner)
graph.add_node("executor",     executor)
graph.add_node("verifier",     verifier)
graph.add_node("auto_process", auto_process)
graph.add_node("human_review", human_review)

# ── Edges ────────────────────────────────────────────────────────────────────────
# 1. Linear flow: planner → executor → verifier
graph.add_edge("planner",  "executor")
graph.add_edge("executor", "verifier")

# 2. After verifier: either loop back to executor OR proceed to routing
graph.add_conditional_edges(
    "verifier",
    route_after_verify,
    {"executor": "executor", "end_routing": "auto_process"}  # default path
)

# 3. From auto_process: check if any loans also need human review
graph.add_conditional_edges(
    "auto_process",
    route_by_risk,
    {"human_review": "human_review", "auto_process": END}
)

# 4. After human review completes → END
graph.add_edge("human_review", END)

# ── Entry point ──────────────────────────────────────────────────────────────────
graph.set_entry_point("planner")

# ── Compile with MemorySaver checkpointer (required for interrupt()) ─────────────
memory = MemorySaver()
app    = graph.compile(checkpointer=memory)

print("✅ LangGraph compiled successfully.")
print("   Nodes :", list(graph.nodes.keys()) if hasattr(graph, 'nodes') else "planner, executor, verifier, auto_process, human_review")
print("   Checkpointer: MemorySaver (enables interrupt/resume)")

"""---
## Step 8 — Define Test Loans

Same 4 test cases from the original `HITLWorkflow` simulation.
"""

# ── Same test loans as the original code ──────────────────────────────────────
# Converted from LoanRequest dataclasses → plain dicts so they
# can travel cleanly through LangGraph's JSON-serialisable state.
test_loans = [
    {
        "application_id":    "APP100301",
        "loan_amount":       500_000,
        "applicant_summary": "Salaried, credit score 720, DTI 30%",
        "ai_recommendation": "Likely approve",
        "risk_score":        0.25,
        "review_required":   False,
        "human_decision":    None,
        "reviewer_id":       None,
        "review_notes":      None,
    },
    {
        "application_id":    "APP100302",
        "loan_amount":       1_500_000,
        "applicant_summary": "Self-employed, credit score 660, DTI 45%",
        "ai_recommendation": "Borderline",
        "risk_score":        0.62,
        "review_required":   False,
        "human_decision":    None,
        "reviewer_id":       None,
        "review_notes":      None,
    },
    {
        "application_id":    "APP100303",
        "loan_amount":       200_000,
        "applicant_summary": "Salaried, credit score 580, DTI 55%",
        "ai_recommendation": "High risk",
        "risk_score":        0.82,
        "review_required":   False,
        "human_decision":    None,
        "reviewer_id":       None,
        "review_notes":      None,
    },
    {
        "application_id":    "APP100304",
        "loan_amount":       800_000,
        "applicant_summary": "Salaried, credit score 750, DTI 25%",
        "ai_recommendation": "Likely approve",
        "risk_score":        0.18,
        "review_required":   False,
        "human_decision":    None,
        "reviewer_id":       None,
        "review_notes":      None,
    },
]

print(f"✅ {len(test_loans)} test loans loaded.")
print("  Expected routing:")
for loan in test_loans:
    flag = (
        loan["loan_amount"] >= HIGH_VALUE_THRESHOLD
        or loan["risk_score"]  >= HIGH_RISK_SCORE
    )
    route = "🔄 human_review" if flag else "⚡ auto_process"
    print(
        f"  [{loan['application_id']}] "
        f"INR {loan['loan_amount']:>12,.0f} | "
        f"Risk {loan['risk_score']:.2f} → {route}"
    )

"""---
## Step 9 — Run Phase 1: Planner → Executor → Verifier → Auto-Process

The graph will run until it hits `interrupt()` inside `human_review`.
At that point execution **pauses** and the cell finishes.  
The state is safely checkpointed in `MemorySaver`.
"""

# ── Thread config — identifies this conversation/run in the checkpointer ────────
thread_config = {"configurable": {"thread_id": "loan_batch_001"}}

# ── Initial state (same pattern as reference notebook) ──────────────────────────
initial_state: LoanState = {
    "goal":            "Evaluate and route a batch of loan applications using risk-based HITL workflow",
    "tasks":           [],
    "loans":           test_loans,
    "processed_loans": [],
    "review_queue":    [],
    "auto_queue":      [],
    "results":         [],
    "critique":        "",
    "approved":        False,
    "iterations":      0,
    "final_decisions": [],
}

print("🚀 Starting LangGraph HITL Loan Approval Workflow...")
print("=" * 65)

# invoke() will run until interrupt() is hit inside human_review
result_phase1 = app.invoke(initial_state, config=thread_config)

print("\n" + "=" * 65)
print("⏸  Graph paused at human_review interrupt.")
print(f"   Auto-processed loans so far: {len(result_phase1.get('final_decisions', []))}")
print(f"   Awaiting human review for  : {len(result_phase1.get('review_queue', []))} loans")

"""---
## Step 10 — Simulate Human Review Decisions

In production an underwriter would see the queued loans in a UI and submit decisions.  
Here we simulate that using `Command(resume=...)`, which feeds the decisions back
into the graph at the exact point where `interrupt()` paused it.

The same decision logic as the original simulation is preserved:  
> `risk_score < 0.70` → APPROVE, else → REJECT
"""

# ── Build simulated underwriter decisions (same logic as original code) ─────────
review_queue_snapshot = result_phase1.get("review_queue", [])

simulated_decisions = []
for i, loan in enumerate(review_queue_snapshot):
    decision_value = (
        ReviewDecision.APPROVE.value
        if loan["risk_score"] < 0.70
        else ReviewDecision.REJECT.value
    )
    simulated_decisions.append({
        "application_id": loan["application_id"],
        "decision":       decision_value,
        "reviewer_id":    f"UNDERWRITER_{i+1:03d}",
        "notes":          "Manual review complete",
    })

print("👤 Simulated underwriter decisions prepared:")
for d in simulated_decisions:
    print(f"   [{d['application_id']}] → {d['decision'].upper()} by {d['reviewer_id']}")

print("\n▶  Resuming graph with Command(resume=...)...")
print("=" * 65)

# ── Resume the graph — this feeds decisions back into human_review node ──────────
result_final = app.invoke(
    Command(resume={"decisions": simulated_decisions}),
    config=thread_config
)

print("\n" + "=" * 65)
print("✅ Graph completed.")

"""---
## Step 11 — Final Summary

Prints the complete outcome for every loan — mirroring the `queue_status()` output
from the original `HITLWorkflow`, but now showing final decisions too.
"""

print("\n" + "═" * 65)
print("📊  FINAL LOAN DECISIONS SUMMARY")
print("═" * 65)

final_decisions = result_final.get("final_decisions", [])

# Count by outcome
counts = {}
for d in final_decisions:
    outcome = d.get("human_decision", "unknown").upper()
    counts[outcome] = counts.get(outcome, 0) + 1

decision_icon = {
    "approve":  "✅",
    "reject":   "❌",
    "escalate": "⚠️",
}

print(f"{'ID':<12} {'Amount (INR)':>14} {'Risk':>6}  {'Route':<14} {'Decision':<10} {'Reviewer'}")
print("-" * 80)

for d in sorted(final_decisions, key=lambda x: x["application_id"]):
    dec   = d.get("human_decision", "unknown")
    icon  = decision_icon.get(dec, "❓")
    route = "human_review" if d.get("review_required") else "auto_process"
    print(
        f"{d['application_id']:<12} "
        f"{d['loan_amount']:>14,.0f} "
        f"{d['risk_score']:>6.2f}  "
        f"{route:<14} "
        f"{icon} {dec:<8} "
        f"{d.get('reviewer_id', 'N/A')}"
    )

print("-" * 80)
print(f"Total: {len(final_decisions)} decisions  |  ", end="")
print("  ".join(f"{k}: {v}" for k, v in counts.items()))

print("\n" + "═" * 65)
print(f"[Verifier] Final score approved after {result_final.get('iterations', 0)} iteration(s)")
print("═" * 65)

"""---
## Notes

| Component | Original Code | This Notebook |
|-----------|--------------|---------------|
| Planner | — | ✅ LLM breaks goal into ≤5 tasks |
| Executor | `HITLWorkflow.route()` | ✅ LLM executes tasks + HITL routing |
| Verifier | — | ✅ LLM-as-judge, loops back if rejected |
| HITL pause | `REVIEW_QUEUE.append()` | ✅ Native `interrupt()` with MemorySaver |
| Resume | `human_review_node()` call | ✅ `Command(resume=...)` |
| Thresholds | `HIGH_VALUE_THRESHOLD`, `HIGH_RISK_SCORE` | ✅ Identical values |
| Test loans | `LoanRequest` dataclasses | ✅ Same 4 loans as plain dicts |
| ReviewDecision | `Enum` | ✅ Same enum, used in decisions |

| LLM | — | ✅ ChatGroq llama-3.1-8b-instant |

>
"""