# -*- coding: utf-8 -*-
"""Day18_Colab1_Agent_FastAPI_Redis_Memory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_ZlWv4J6WIRsAw_AOHAg0dJkSheyyo3

# Day 18 · Colab 1 — Claude Agent + FastAPI Backend + Redis Memory

**Agentic Systems Bootcamp**

In this notebook you build a small but complete **tool-using agent**:

- a **FastAPI** backend exposing an `/orders/{id}` endpoint (your *external API*),
- a **Redis** memory layer (short-term conversation history + long-term facts),
- a **Claude** agent that calls tools in a `while` loop driven by `stop_reason`.

Everything runs **inside Colab** with no external servers:
`fakeredis` stands in for Redis and FastAPI's `TestClient` calls the API in-process.
Swap either for the real thing by changing one line each (shown at the end).

> **Pattern recap (from the deck):** client tools return `stop_reason="tool_use"`; *your* code runs the
> tool and returns a `tool_result` block; you loop until `stop_reason="end_turn"`.

## Step 1 — Install dependencies & set your API key

`fakeredis` gives us a real Redis API surface in-process. `httpx` is needed by FastAPI's test client.
"""

!pip install -q anthropic fastapi 'httpx<0.28' fakeredis 2>/dev/null
print('deps installed')

import os, getpass

# In Colab, prefer the Secrets panel (key icon) named ANTHROPIC_API_KEY.
if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass

if not os.environ.get('ANTHROPIC_API_KEY'):
    # Fallback: paste it (hidden). Leave blank to run in OFFLINE mock mode.
    os.environ['ANTHROPIC_API_KEY'] = getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): ')

LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'  # fast + cheap for a workshop; opus-4-8 for harder reasoning
print('LIVE mode' if LIVE else 'OFFLINE mock mode (no key) — agent loop will be simulated')

"""## Step 2 — A tiny FastAPI backend (the 'external API')

This is the kind of service your agent does **not** control — it just calls it.
We expose one route, then wrap the app in a `TestClient` so calls run in-process.
"""

from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient

app = FastAPI()

_ORDERS = {
    'A1001': {'id': 'A1001', 'item': 'Mechanical keyboard', 'qty': 1, 'status': 'shipped',  'total': 129.0},
    'A1002': {'id': 'A1002', 'item': 'USB-C hub',          'qty': 2, 'status': 'processing','total': 58.0},
    'A1003': {'id': 'A1003', 'item': '4K monitor',         'qty': 1, 'status': 'delivered', 'total': 410.0},
}

@app.get('/orders/{order_id}')
def get_order(order_id: str):
    o = _ORDERS.get(order_id.upper())
    if not o:
        raise HTTPException(status_code=404, detail='order not found')
    return o

client = TestClient(app)
print(client.get('/orders/A1001').json())

"""## Step 3 — A Redis memory layer

Two responsibilities, the way the deck framed memory:

- **Short-term** — the running conversation, stored as a Redis **list** per session (`hist:<session>`).
- **Long-term** — durable **facts** about the user, stored in a Redis **hash** (`facts:<session>`), with an optional TTL.

`fakeredis` implements the same commands, so this class is unchanged when you move to real Redis.
"""

import json, time, fakeredis

class RedisMemory:
    def __init__(self, r, session_id: str, history_limit: int = 40):
        self.r = r
        self.sid = session_id
        self.history_limit = history_limit
        self.h_key = f'hist:{session_id}'
        self.f_key = f'facts:{session_id}'

    # ---- short-term: conversation turns ----
    def append_turn(self, role: str, content):
        self.r.rpush(self.h_key, json.dumps({'role': role, 'content': content}))
        self.r.ltrim(self.h_key, -self.history_limit, -1)  # keep only the tail

    def load_history(self):
        return [json.loads(x) for x in self.r.lrange(self.h_key, 0, -1)]

    # ---- long-term: durable facts ----
    def set_fact(self, key: str, value: str, ttl_seconds: int | None = None):
        self.r.hset(self.f_key, key, value)
        if ttl_seconds:
            self.r.expire(self.f_key, ttl_seconds)

    def get_fact(self, key: str):
        v = self.r.hget(self.f_key, key)
        return v.decode() if isinstance(v, bytes) else v

    def all_facts(self):
        return {k.decode(): v.decode() for k, v in self.r.hgetall(self.f_key).items()}

r = fakeredis.FakeStrictRedis()
mem = RedisMemory(r, session_id='demo-user')
mem.set_fact('name', 'Asha')
mem.append_turn('user', 'hello')
print('facts:', mem.all_facts())
print('history:', mem.load_history())

"""## Step 4 — Declare the tools (JSON schemas)

Three client tools. Names are **namespaced by purpose** and every field is described —
the description *is* the prompt the model reads when deciding how to call.
`order_id` uses a `pattern` so the model returns well-formed IDs.
"""

TOOLS = [
    {
        'name': 'get_order',
        'description': 'Look up a customer order by its ID and return item, quantity, status and total.',
        'input_schema': {
            'type': 'object',
            'properties': {
                'order_id': {'type': 'string', 'description': "Order ID like 'A1001'.", 'pattern': '^[Aa][0-9]{4}$'}
            },
            'required': ['order_id'],
        },
    },
    {
        'name': 'remember_fact',
        'description': 'Persist a durable fact about the user (e.g. shipping preference) for future turns.',
        'input_schema': {
            'type': 'object',
            'properties': {
                'key':   {'type': 'string', 'description': 'Short fact key, e.g. "shipping_pref".'},
                'value': {'type': 'string', 'description': 'The fact value to store.'},
            },
            'required': ['key', 'value'],
        },
    },
    {
        'name': 'recall_fact',
        'description': 'Retrieve a previously stored fact about the user by key. Returns empty if unknown.',
        'input_schema': {
            'type': 'object',
            'properties': {'key': {'type': 'string', 'description': 'The fact key to look up.'}},
            'required': ['key'],
        },
    },
]
print(len(TOOLS), 'tools declared')

"""## Step 5 — A dispatch map: tool name → Python function

This is the boundary between *the model's intent* and *your code*. Each function returns a
string (what the model will read back). Errors are **returned**, not raised, so the agent can recover —
that maps to `is_error: true` on the `tool_result` block in Step 6.
"""

def tool_get_order(order_id: str):
    resp = client.get(f'/orders/{order_id}')
    if resp.status_code == 404:
        return {'error': f'No order {order_id} found.'}
    resp.raise_for_status()
    return resp.json()

def tool_remember_fact(key: str, value: str):
    mem.set_fact(key, value)
    return {'ok': True, 'stored': {key: value}}

def tool_recall_fact(key: str):
    v = mem.get_fact(key)
    return {'key': key, 'value': v} if v is not None else {'key': key, 'value': None}

DISPATCH = {
    'get_order': tool_get_order,
    'remember_fact': tool_remember_fact,
    'recall_fact': tool_recall_fact,
}

def run_tool(name, args):
    fn = DISPATCH.get(name)
    if fn is None:
        return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        is_err = isinstance(out, dict) and 'error' in out
        return out, is_err
    except Exception as e:
        return {'error': repr(e)}, True

print(run_tool('get_order', {'order_id': 'A1002'}))
print(run_tool('get_order', {'order_id': 'A9999'}))

"""## Step 6 — The agent loop (driven by `stop_reason`)

This is the heart of client-side tool use:

1. send messages + tool definitions,
2. if `stop_reason == 'tool_use'`: run **every** `tool_use` block, append a single user message
   containing one `tool_result` per call (matched by `tool_use_id`), and loop,
3. stop at `stop_reason == 'end_turn'` and return the text.

If there's no API key we simulate one scripted tool call so the notebook still runs end-to-end.
"""

import json

SYSTEM = (
    'You are an order-support assistant. Use get_order for any order question. '
    'Use remember_fact / recall_fact to keep durable user preferences across turns. '
    'Be concise.'
)

def agent_turn(user_text, max_steps=6, verbose=True):
    mem.append_turn('user', user_text)
    messages = mem.load_history()

    if not LIVE:
        # ---- offline mock: pretend the model asked for get_order once ----
        if verbose: print('… (mock) model requests get_order A1001')
        out, _ = run_tool('get_order', {'order_id': 'A1001'})
        reply = f'(mock) Order A1001 is {out.get("status", "?")}.'
        mem.append_turn('assistant', reply)
        return reply

    from anthropic import Anthropic
    clientA = Anthropic()
    for step in range(max_steps):
        resp = clientA.messages.create(
            model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages,
        )
        if resp.stop_reason == 'tool_use':
            # echo the assistant turn (text + tool_use blocks) back into the transcript
            messages.append({'role': 'assistant', 'content': [b.model_dump() for b in resp.content]})
            results = []
            for block in resp.content:
                if block.type == 'tool_use':
                    if verbose: print(f'  → tool: {block.name}({block.input})')
                    out, is_err = run_tool(block.name, block.input)
                    results.append({
                        'type': 'tool_result',
                        'tool_use_id': block.id,
                        'content': json.dumps(out),
                        'is_error': is_err,
                    })
            messages.append({'role': 'user', 'content': results})
            continue
        # end_turn
        text = ''.join(b.text for b in resp.content if b.type == 'text')
        mem.append_turn('assistant', text)
        return text
    return '(stopped: max steps reached)'

print(agent_turn('What is the status of order A1002?'))

"""## Step 7 — Persistence check: memory survives across turns

Because every turn is written to Redis, a fresh `agent_turn` call still sees the history and facts.
Ask the agent to remember something, then recall it in a later turn.
"""

print(agent_turn('Please remember that my shipping preference is express.'))
print('---')
print(agent_turn('What did I say my shipping preference was?'))
print('---')
print('Raw facts in Redis:', mem.all_facts())
print('History length:', len(mem.load_history()), 'turns')

"""## Step 8 — Multi-turn chat demo

A short scripted conversation that exercises lookup + memory together.
"""

for msg in [
    'Hi, I am Asha.',
    'How much was order A1003?',
    'Remember that my budget cap is 500 dollars.',
    'Given my budget cap, was that order within it?',
]:
    print('USER:', msg)
    print('AGENT:', agent_turn(msg, verbose=False))
    print()

"""## Extension tasks

Pick a few — these are the assignment for this lab.

1. **Rolling summary / compaction.** When `load_history()` exceeds N turns, summarise the oldest
   turns with a cheap model call and replace them with one synthetic `assistant` summary message.
   Keep total context bounded.
2. **TTL & a `forget` tool.** Add a `forget_fact(key)` tool and give facts a TTL via `set_fact(..., ttl_seconds=...)`.
   Show that an expired fact returns `None`.
3. **Parallel lookups.** Add a `get_customer` tool and a second order endpoint, then ask a question that
   needs both — observe Claude emit **two `tool_use` blocks in one turn**. Confirm your loop answers both ids.
4. **Guarded writes / PII.** Reject `remember_fact` values that look like card numbers or emails (regex);
   return `is_error: true` with a helpful message and confirm the agent recovers.
5. **Token accounting.** Read `resp.usage` each step; print cumulative input/output tokens for a turn.
6. **Real Redis.** Replace `fakeredis.FakeStrictRedis()` with `redis.Redis.from_url(os.environ['REDIS_URL'])`
   (e.g. a free Upstash/Redis Cloud URL). The `RedisMemory` class should not change at all.

> **Stretch:** swap `TestClient` for a real deployed FastAPI URL using `httpx.Client(base_url=...)`.
> Only `tool_get_order` changes; the agent loop is untouched.
"""

# ============================================================
# EXTENSION TASK 1 — Rolling Summary / Compaction
# When conversation history exceeds COMPACTION_THRESHOLD turns,
# the oldest turns are summarised into one synthetic assistant
# message using a cheap Claude call. The recent KEEP_RECENT
# turns are preserved untouched. This keeps the Redis list and
# the context window bounded so long sessions never blow up.
# ============================================================

import json
from anthropic import Anthropic

COMPACTION_THRESHOLD = 6   # trigger compaction when history exceeds this
KEEP_RECENT          = 2   # always preserve this many most-recent turns

def compact_history_if_needed(mem_arg, verbose=True):
    """
    Checks if history exceeds COMPACTION_THRESHOLD.
    If so: summarises the oldest turns via Claude, replaces them
    with one synthetic assistant summary message, and rewrites
    the Redis list. Returns True if compaction ran, False otherwise.
    """
    history = mem_arg.load_history()
    if len(history) <= COMPACTION_THRESHOLD:
        if verbose:
            print(f"History has {len(history)} turns — no compaction needed.")
        return False

    old_turns    = history[:-KEEP_RECENT]   # turns to compress
    recent_turns = history[-KEEP_RECENT:]   # turns to keep intact

    # Build a plain-text transcript of the old turns for the summariser
    transcript = "\n".join(
        f"{t['role'].upper()}: "
        + (t['content'] if isinstance(t['content'], str)
           else json.dumps(t['content']))
        for t in old_turns
    )

    if LIVE:
        clientA = Anthropic()
        summary_resp = clientA.messages.create(
            model=MODEL,
            max_tokens=256,
            messages=[{
                "role": "user",
                "content": (
                    "Summarise the following conversation excerpt in 2-3 sentences, "
                    "preserving any key facts (orders, preferences, names):\n\n"
                    + transcript
                )
            }]
        )
        summary_text = summary_resp.content[0].text
    else:
        summary_text = (
            "(mock summary) User introduced themselves, asked about orders "
            "A1001 and A1003, and set their shipping preference to express."
        )

    # Compacted history = 1 summary turn + the KEEP_RECENT most recent turns
    compacted = [{
        "role": "assistant",
        "content": f"[Summary of earlier conversation]: {summary_text}"
    }]
    compacted += recent_turns

    # Overwrite the Redis list with the compacted version
    mem_arg.r.delete(mem_arg.h_key)
    for turn in compacted:
        mem_arg.append_turn(turn["role"], turn["content"])

    if verbose:
        print(f"Compacted {len(old_turns)} old turns → 1 summary message.")
        print(f"History now has {len(mem_arg.load_history())} turns "
              f"(1 summary + {KEEP_RECENT} recent).")
        print(f"Summary text: {summary_text}")
    return True


# ---- Test ----
r_task1  = fakeredis.FakeStrictRedis()
mem_task1 = RedisMemory(r_task1, session_id='task1-user', history_limit=40)
mem_task1.set_fact('name', 'Asha')

# Fill history past the threshold
dummy_turns = [
    ("user",      "Hi, I am Asha."),
    ("assistant", "Hello Asha! How can I help?"),
    ("user",      "What is the status of order A1001?"),
    ("assistant", "Order A1001 (Mechanical keyboard) is shipped."),
    ("user",      "Remember my shipping preference is express."),
    ("assistant", "Got it, I have saved your shipping preference as express."),
    ("user",      "How much was order A1003?"),
    ("assistant", "Order A1003 (4K monitor) totalled $410."),
]
for role, content in dummy_turns:
    mem_task1.append_turn(role, content)

print(f"History before compaction: {len(mem_task1.load_history())} turns")
compact_history_if_needed(mem_task1, verbose=True)

print("\nFirst turn after compaction (the summary):")
print(mem_task1.load_history()[0]['content'])
print("\nLast 2 turns preserved:")
for t in mem_task1.load_history()[1:]:
    print(f"  [{t['role']}]: {t['content']}")

# ============================================================
# EXTENSION TASK 2 — TTL & a forget_fact Tool
# A new forget_fact tool lets the agent delete a specific fact
# from Redis on the user's request. Facts can also be given a
# TTL (time-to-live) via set_fact(..., ttl_seconds=...) so they
# expire automatically. Both are tested: forget_fact via
# run_tool() exactly as the agent would call it, and TTL via
# time.sleep() to confirm an expired fact returns None.
# ============================================================

import time

# ---- New tool function — uses the global mem (same as all other tools) ----
def tool_forget_fact(key: str):
    """Delete a single fact from Redis. Returns an error if the key does not exist."""
    existing = mem.get_fact(key)
    if existing is None:
        return {"ok": False, "message": f"No fact found for key '{key}'."}
    mem.r.hdel(mem.f_key, key)
    return {"ok": True, "deleted_key": key}

# Register in DISPATCH so run_tool() can find it
DISPATCH["forget_fact"] = tool_forget_fact

# Add JSON schema so Claude knows it can call this tool
TOOLS.append({
    "name": "forget_fact",
    "description": (
        "Delete a previously stored fact about the user by key. "
        "Use when the user asks to remove or forget a preference."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "key": {
                "type": "string",
                "description": "The fact key to delete, e.g. 'shipping_pref'."
            }
        },
        "required": ["key"],
    },
})
print(f"TOOLS now has {len(TOOLS)} tools: {[t['name'] for t in TOOLS]}")


# ---- Test 1: forget_fact called exactly as the agent would via run_tool() ----
# Store two facts in the GLOBAL mem so tool_forget_fact operates on the right session
mem.set_fact("shipping_pref", "express")
mem.set_fact("budget_cap",    "500")
print("\nFacts before forget:", mem.all_facts())

result, is_err = run_tool("forget_fact", {"key": "shipping_pref"})
print(f"run_tool result: {result}  |  is_error={is_err}")
print("Facts after forget:", mem.all_facts())

# Confirm deleted key returns None on recall
recalled, _ = run_tool("recall_fact", {"key": "shipping_pref"})
print(f"Recall deleted key: {recalled}")   # {'key': 'shipping_pref', 'value': None}

# Attempt to forget an already-deleted key
result2, is_err2 = run_tool("forget_fact", {"key": "shipping_pref"})
print(f"Double-delete: {result2}  |  is_error={is_err2}")


# ---- Test 2: TTL expiry ----
# Store a fact with a short TTL and confirm it disappears after expiry.
# Note: TTL applies to the entire facts hash (Redis EXPIRE on the hash key),
# so ALL facts in that session expire together. This is the behaviour built
# into the existing set_fact() method.
r_ttl  = fakeredis.FakeStrictRedis()
mem_ttl = RedisMemory(r_ttl, session_id='ttl-test-user')

mem_ttl.set_fact("promo_code", "SAVE10", ttl_seconds=2)
print(f"\nFact immediately after set : {mem_ttl.get_fact('promo_code')}")  # SAVE10

time.sleep(3)   # wait for TTL to expire

val_after = mem_ttl.get_fact("promo_code")
print(f"Fact after TTL expiry      : {val_after}")   # None
assert val_after is None, "Expected None after TTL expiry!"
print("TTL expiry confirmed ✓")

# ============================================================
# EXTENSION TASK 3 — Parallel Tool Calls
# A second FastAPI endpoint (GET /customers/{id}) and a new
# get_customer tool are added. The SYSTEM prompt is updated so
# Claude knows to use it. When asked a question that needs BOTH
# an order and a customer lookup, Claude emits TWO tool_use
# blocks in a single turn. The existing agent loop already
# handles this because it iterates all blocks in resp.content —
# this task proves it and makes both calls visible.
# ============================================================

from fastapi import HTTPException   # already imported but explicit for clarity

# ---- Extend FastAPI with a /customers endpoint ----
_CUSTOMERS = {
    "C001": {"id": "C001", "name": "Asha Mehta",  "email": "asha@example.com",  "tier": "gold"},
    "C002": {"id": "C002", "name": "Rohan Gupta", "email": "rohan@example.com", "tier": "silver"},
}

@app.get("/customers/{customer_id}")
def get_customer_endpoint(customer_id: str):
    c = _CUSTOMERS.get(customer_id.upper())
    if not c:
        raise HTTPException(status_code=404, detail="customer not found")
    return c

# Reassign client so it wraps the updated app with the new route
client = TestClient(app)
print("New /customers route test:", client.get("/customers/C001").json())


# ---- New tool function ----
def tool_get_customer(customer_id: str):
    resp = client.get(f"/customers/{customer_id}")
    if resp.status_code == 404:
        return {"error": f"No customer {customer_id} found."}
    resp.raise_for_status()
    return resp.json()

# Register in DISPATCH
DISPATCH["get_customer"] = tool_get_customer

# Add JSON schema
TOOLS.append({
    "name": "get_customer",
    "description": "Look up a customer by their ID (e.g. C001) and return name, email and tier.",
    "input_schema": {
        "type": "object",
        "properties": {
            "customer_id": {
                "type": "string",
                "description": "Customer ID like 'C001'.",
                "pattern": "^[Cc][0-9]{3}$"
            }
        },
        "required": ["customer_id"],
    },
})

# ---- CRITICAL: update SYSTEM prompt so Claude knows about get_customer ----
# Without this, Claude won't know the tool exists and won't emit a parallel call.
SYSTEM = (
    'You are an order-support assistant. '
    'Use get_order for any order question. '
    'Use get_customer to look up a customer by customer ID (e.g. C001). '
    'Use remember_fact / recall_fact to keep durable user preferences across turns. '
    'Be concise.'
)
print(f"\nTOOLS now has {len(TOOLS)} tools: {[t['name'] for t in TOOLS]}")
print("SYSTEM prompt updated to include get_customer.")


# ---- Direct tool tests ----
print("\nDirect tool tests:")
print("  get_customer C001:", run_tool("get_customer", {"customer_id": "C001"}))
print("  get_customer C999:", run_tool("get_customer", {"customer_id": "C999"}))


# ---- Parallel agent turn ----
# This prompt is designed to make Claude call BOTH get_order AND get_customer
# in a single response turn. Watch for two "→ tool:" lines before the answer.
r_task3  = fakeredis.FakeStrictRedis()
mem_task3 = RedisMemory(r_task3, session_id='task3-user')

_original_mem = mem
mem = mem_task3

print("\nSending prompt that should trigger parallel tool calls …\n")
response = agent_turn(
    "I need you to simultaneously look up order A1003 AND customer C001 "
    "and tell me all the details for both.",
    verbose=True
)
print("\nAgent final answer:", response)

mem = _original_mem

# ============================================================
# EXTENSION TASK 4 — Guarded Writes / PII Rejection
# The remember_fact tool now rejects values that look like
# email addresses or credit card numbers (15-16 digit sequences).
# It returns is_error=True with a clear explanation so the agent
# can relay the refusal to the user and recover gracefully —
# the loop never crashes, it just handles the error result.
# ============================================================

import re

# ---- PII detection patterns ----
_EMAIL_RE = re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+")
_CC_RE    = re.compile(r"\b(?:\d[ -]?){15,16}\b")  # matches 15-16 digit card numbers

def contains_pii(value: str):
    """Returns a reason string if PII is detected, or None if clean."""
    if _EMAIL_RE.search(value):
        return "email address"
    # Strip separators before checking card pattern
    if _CC_RE.search(value.replace(" ", "").replace("-", "")):
        return "credit card number"
    return None


# ---- Patched tool_remember_fact with PII guard ----
def tool_remember_fact(key: str, value: str):
    pii_reason = contains_pii(value)
    if pii_reason:
        # Returning a dict with 'error' key causes run_tool() to set is_error=True
        return {
            "error": (
                f"Refused: the value looks like a {pii_reason}. "
                "I cannot store PII such as emails or card numbers."
            )
        }
    mem.set_fact(key, value)
    return {"ok": True, "stored": {key: value}}

# Patch into DISPATCH — replaces the original tool_remember_fact
DISPATCH["remember_fact"] = tool_remember_fact
print("remember_fact patched with PII guard.\n")


# ---- Unit tests covering all cases ----
print("=== PII Guard Unit Tests ===\n")
test_cases = [
    ("city",    "Bengaluru",             False, "clean string"),
    ("contact", "asha@example.com",      True,  "email address"),
    ("card",    "4111 1111 1111 1111",   True,  "card with spaces"),
    ("card",    "4111-1111-1111-1111",   True,  "card with dashes"),
    ("card",    "4111111111111111",       True,  "card no separators"),
    ("note",    "my order is 12345678",  False, "8-digit number — must NOT block"),
]
all_pass = True
for key, value, should_block, desc in test_cases:
    _, is_err = run_tool("remember_fact", {"key": key, "value": value})
    status = "PASS" if is_err == should_block else "FAIL"
    if status == "FAIL": all_pass = False
    print(f"  [{status}] {desc}")
print(f"\nAll unit tests: {'PASSED ✓' if all_pass else 'FAILURES — check above'}")


# ---- Live agent recovery test (LIVE mode only) ----
# The agent receives is_error=True and should tell the user why storage was refused.
if LIVE:
    print("\n=== Agent Recovery Test ===\n")
    r_task4  = fakeredis.FakeStrictRedis()
    mem_task4 = RedisMemory(r_task4, session_id='task4-user')
    _original_mem = mem
    mem = mem_task4
    response = agent_turn(
        "Please remember my email as asha@example.com for future contact.",
        verbose=True
    )
    print("Agent response:", response)
    # Confirm nothing was stored
    print("Facts in Redis after refused write:", mem.all_facts())
    mem = _original_mem
else:
    print("\n(OFFLINE mode — skipping live recovery test)")
    print("In LIVE mode the agent would receive is_error=True and tell the user")
    print("it cannot store email addresses, then continue the conversation normally.")

# ============================================================
# EXTENSION TASK 5 — Token Accounting
# After every Claude API call inside the agent loop, resp.usage
# provides input_tokens and output_tokens. This version of the
# agent loop accumulates those counts across all steps in a
# turn and prints a per-step table plus a cumulative total with
# an estimated USD cost based on claude-sonnet-4-6 pricing.
# ============================================================

# Pricing per million tokens for claude-sonnet-4-6 (mid-2025 rates)
PRICE_INPUT_PER_M  = 3.00   # USD per 1M input tokens
PRICE_OUTPUT_PER_M = 15.00  # USD per 1M output tokens

def estimate_cost(input_tokens: int, output_tokens: int) -> float:
    return (input_tokens  / 1_000_000 * PRICE_INPUT_PER_M +
            output_tokens / 1_000_000 * PRICE_OUTPUT_PER_M)


def agent_turn_with_tokens(user_text: str, max_steps: int = 6, verbose: bool = True):
    """
    Identical to agent_turn() but instruments every API call with token
    reporting. Prints a per-step row and a cumulative total at the end.
    """
    mem.append_turn("user", user_text)
    messages = mem.load_history()

    if not LIVE:
        print("(OFFLINE mode — no real API calls, no token data)")
        out, _ = run_tool("get_order", {"order_id": "A1001"})
        reply = f"(mock) Order A1001 is {out.get('status', '?')}."
        mem.append_turn("assistant", reply)
        return reply

    from anthropic import Anthropic
    clientA = Anthropic()

    total_input = total_output = 0
    print(f"\n{'Step':<6} {'In tokens':>10} {'Out tokens':>11} {'Step cost $':>12}")
    print("-" * 44)

    for step in range(max_steps):
        resp = clientA.messages.create(
            model=MODEL, max_tokens=1024, system=SYSTEM,
            tools=TOOLS, messages=messages,
        )

        # --- Per-step token accounting ---
        in_tok  = resp.usage.input_tokens
        out_tok = resp.usage.output_tokens
        total_input  += in_tok
        total_output += out_tok
        step_cost = estimate_cost(in_tok, out_tok)
        print(f"{step + 1:<6} {in_tok:>10,} {out_tok:>11,} {step_cost:>12.5f}")

        if resp.stop_reason == "tool_use":
            messages.append({
                "role": "assistant",
                "content": [b.model_dump() for b in resp.content]
            })
            results = []
            for block in resp.content:
                if block.type == "tool_use":
                    if verbose:
                        print(f"  → tool: {block.name}({block.input})")
                    out, is_err = run_tool(block.name, block.input)
                    results.append({
                        "type":        "tool_result",
                        "tool_use_id": block.id,
                        "content":     json.dumps(out),
                        "is_error":    is_err,
                    })
            messages.append({"role": "user", "content": results})
            continue

        # end_turn — extract reply, save to Redis, print summary
        text = "".join(b.text for b in resp.content if b.type == "text")
        mem.append_turn("assistant", text)

        total_cost = estimate_cost(total_input, total_output)
        print("-" * 44)
        print(f"{'TOTAL':<6} {total_input:>10,} {total_output:>11,} {total_cost:>12.5f}")
        print(f"\nAgent: {text}")
        return text

    return "(stopped: max steps reached)"


# ---- Test ----
r_task5  = fakeredis.FakeStrictRedis()
mem_task5 = RedisMemory(r_task5, session_id='task5-user')

# Swap global mem for this test, then restore after
_original_mem = mem
mem = mem_task5

print("Running token-tracked agent turn …")
agent_turn_with_tokens("What is the total cost of order A1003?", verbose=True)

# Restore global mem — must be OUTSIDE the function so it always executes
mem = _original_mem
print("\nGlobal mem restored ✓")

# ============================================================
# EXTENSION TASK 6 — Real Redis (One-Line Swap)
# Replace fakeredis.FakeStrictRedis() with a real Redis client
# using redis.Redis.from_url(). The RedisMemory class does NOT
# change at all — proving the abstraction is correct.
#
# HOW TO GET A FREE REDIS URL (pick one):
#   Upstash    → https://upstash.com  → create DB → copy "Redis URL"
#   Redis Cloud→ https://redis.io/try-free
#   URL format → redis://default:<password>@<host>:<port>
#
# Add it as a Colab Secret named REDIS_URL (key icon in sidebar),
# or paste it when prompted below.
# ============================================================

import os, sys, subprocess

# ---- Install redis package if not already present ----
try:
    import redis as redis_lib
except ImportError:
    print("Installing redis package …")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "redis"])
    import redis as redis_lib
    print("redis installed.")

# ---- Resolve the Redis URL ----
redis_url = os.environ.get("REDIS_URL", "")

if not redis_url:
    try:
        from google.colab import userdata
        redis_url = userdata.get("REDIS_URL") or ""
    except Exception:
        pass

if not redis_url:
    redis_url = input(
        "Paste your Redis URL (e.g. redis://default:pass@host:port), "
        "or press Enter to use fakeredis: "
    ).strip()

# ---- Connect — real Redis or fakeredis fallback ----
USE_REAL = False
if redis_url:
    try:
        r_real = redis_lib.Redis.from_url(
            redis_url,
            decode_responses=False,  # keep bytes so RedisMemory.get_fact .decode() works
            socket_timeout=5,
            socket_connect_timeout=5,
        )
        r_real.ping()   # raises ConnectionError immediately if URL is wrong
        masked = redis_url.split("@")[-1]   # hide password in logs
        print(f"✅ Connected to REAL Redis at: {masked}")
        USE_REAL = True
    except Exception as e:
        print(f"⚠️  Could not connect to real Redis ({e}). Falling back to fakeredis.")
        r_real = fakeredis.FakeStrictRedis()
else:
    print("No URL provided — using fakeredis (behaviour is identical to real Redis).")
    r_real = fakeredis.FakeStrictRedis()

# ---- THE ONE-LINE SWAP — RedisMemory is completely unchanged ----
mem_real = RedisMemory(r_real, session_id="real-redis-user")

# ---- Smoke test: set, recall, forget, history ----
mem_real.set_fact("name", "Asha")
mem_real.set_fact("tier", "gold")
mem_real.append_turn("user",      "Hello from real Redis!")
mem_real.append_turn("assistant", "Hi Asha! I remember you.")

print("\n--- Smoke test ---")
print("All facts  :", mem_real.all_facts())
print("History    :", mem_real.load_history())
print("Recall name:", mem_real.get_fact("name"))
print("Recall tier:", mem_real.get_fact("tier"))

assert mem_real.get_fact("name") == "Asha"
assert mem_real.get_fact("tier") == "gold"
assert len(mem_real.load_history()) == 2
print("\nSmoke test PASSED ✓")

# ---- Optional: run a full agent turn against real Redis (LIVE mode only) ----
if LIVE and USE_REAL:
    print("\n--- Full agent turn on real Redis ---")
    _original_mem = mem
    mem = mem_real
    result = agent_turn("What is the status of order A1002?", verbose=True)
    print("Agent:", result)
    mem = _original_mem
    print(f"\nHistory now in real Redis: {len(mem_real.load_history())} turns")
    print("Facts in real Redis:", mem_real.all_facts())
else:
    print(f"\n(Full agent turn skipped — LIVE={LIVE}, USE_REAL={USE_REAL})")
    print("To run it: set ANTHROPIC_API_KEY and provide a valid REDIS_URL above.")