# -*- coding: utf-8 -*-
"""Day_14_Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbWtzQ1aS70cpG5XnyWIq0kC0owCQpmv
"""

# Install libraries used for semantic similarity
!pip install -q bert-score sentence-transformers transformers torch numpy

!pip install -q transformers torch sentencepiece

"""
BERTScore

Purpose:
--------
Measures semantic similarity between:
1. Generated answer
2. Ground truth (reference answer)

Use Case:
---------
Higher score indicates generated response is
semantically close to the expected answer.

Output:
-------
Precision
Recall
F1 Score (most commonly used)
"""

from bert_score import score

candidate = "Paris is the capital city of France."
reference = "The capital of France is Paris."

P, R, F1 = score(
    [candidate],
    [reference],
    lang="en"
)

print("===== BERTScore Results =====")
print("Precision:", float(P[0]))
print("Recall:", float(R[0]))
print("F1 Score:", float(F1[0]))

"""
SelfCheckGPT

Purpose:
--------
Detect hallucinations by checking whether
multiple model generations agree with each other.

Idea:
-----
If the model gives highly different answers
for the same question, confidence decreases.

Higher consistency = Lower hallucination risk.
"""

from sentence_transformers import SentenceTransformer, util
import numpy as np

# Lightweight embedding model
model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

# Multiple responses generated for the same prompt
responses = [
    "Paris is the capital of France.",
    "France's capital city is Paris.",
    "Paris serves as the capital of France."
]

# Convert responses into embeddings
embeddings = model.encode(
    responses,
    convert_to_tensor=True
)

similarities = []

# Calculate pairwise similarity
for i in range(len(responses)):
    for j in range(i + 1, len(responses)):

        sim = util.cos_sim(
            embeddings[i],
            embeddings[j]
        ).item()

        similarities.append(sim)

selfcheck_score = np.mean(similarities)

print("\n===== SelfCheckGPT Results =====")
print("Consistency Score:", selfcheck_score)

if selfcheck_score > 0.85:
    print("Low hallucination risk")
elif selfcheck_score > 0.70:
    print("Moderate hallucination risk")
else:
    print("High hallucination risk")

"""
FactScore (Simplified)

Purpose:
--------
Measures whether individual factual claims
are supported by retrieved evidence.

Official FactScore uses:
1. Claim Extraction
2. Retrieval
3. Verification

This demo uses embedding similarity as a proxy.
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

# Claims extracted from generated answer
facts = [
    "Paris is the capital of France",
    "France is located in Europe"
]

# Retrieved evidence from trusted source
evidence_docs = [
    "Paris is the capital city of France.",
    "France is a country in Europe."
]

evidence_embeddings = model.encode(
    evidence_docs,
    convert_to_tensor=True
)

supported_facts = 0

for fact in facts:

    fact_embedding = model.encode(
        fact,
        convert_to_tensor=True
    )

    similarity = util.cos_sim(
        fact_embedding,
        evidence_embeddings
    ).max().item()

    print(f"\nFact: {fact}")
    print("Support Similarity:", similarity)

    if similarity > 0.75:
        supported_facts += 1

factscore = supported_facts / len(facts)

print("\n===== FactScore Results =====")
print("FactScore:", factscore)

"""
HHEM-like Hallucination Detection (No API)

Purpose:
--------
Checks whether a claim is supported by context.

Model:
------
facebook/bart-large-mnli

Output:
-------
Hallucination Probability
"""

from transformers import pipeline

# Load model
classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

# Claim generated by LLM
claim = "Paris is the capital of France"

# Retrieved context / source document
context = """
Paris is the capital and most populous city of France.
"""

labels = [
    "supported by context",
    "contradicted by context",
    "not enough information"
]

result = classifier(
    claim,
    labels,
    hypothesis_template="This statement is {}."
)

print("\n===== HHEM-like Results =====")

for label, score in zip(
    result["labels"],
    result["scores"]
):
    print(f"{label}: {score:.4f}")

hallucination_probability = next(
    score
    for label, score in zip(
        result["labels"],
        result["scores"]
    )
    if label == "contradicted by context"
)

print(
    f"\nHallucination Probability: "
    f"{hallucination_probability:.4f}"
)