# -*- coding: utf-8 -*-
"""Day18_Colab2_Chaining_Redis_Event_Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IyC9rMU5uhEjUPdVJEEnuwkXamUn6j0b

# Day 18 · Colab 2 — Multi-tool Agent Chaining + Redis Event Queue

**Agentic Systems Bootcamp**

Here the agent does real **orchestration**: it *chains* tools to place an order —
`check_inventory → create_order → send_confirmation` — mixing **synchronous** tools
(SQLite reads/writes) with an **asynchronous** one (enqueue an email job onto a Redis Stream,
handled later by a separate **worker** via a consumer group).

Runs entirely in Colab: `fakeredis` provides `XADD` / `XREADGROUP`, SQLite is built in.

> **Patterns (from the deck):** *routing* (pick the right tool), *prompt chaining* (feed one tool's
> output into the next), *parallel* reads, and the **sync-vs-async** boundary — slow side-effects go
> on a queue so the agent turn stays fast.

## Step 1 — Install & configure
"""

!pip install -q anthropic fakeredis 2>/dev/null
import os, getpass
if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass
if not os.environ.get('ANTHROPIC_API_KEY'):
    os.environ['ANTHROPIC_API_KEY'] = getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): ')
LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'
print('LIVE mode' if LIVE else 'OFFLINE mock mode')

"""## Step 2 — SQLite orders + inventory database

Two tables: `inventory` (stock per SKU) and `orders` (what we create).
All access is through **parameterised** SQL — never string-formatted — and reads are row-limited.
"""

import sqlite3
db = sqlite3.connect(':memory:', check_same_thread=False)
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('inventory seeded')

"""## Step 3 — A Redis Stream as the email job queue

`send_confirmation` won't send email inline (slow, can fail). It **enqueues** a job with `XADD` and
returns a `job_id` immediately. A **worker** later reads with `XREADGROUP` (a consumer group gives us
at-least-once delivery + acks) and writes the result back to a `jobresult:<id>` key.
"""

import fakeredis, json, time, uuid
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
except Exception as e:
    print('group exists:', e)

def enqueue_email(to, subject, body):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; sample job id ->', enqueue_email('a@x.com', 'hi', 'test'))

"""## Step 4 — The worker (consumer group)

In production this is a separate process. Here we drain the stream on demand. Each message is
processed, the result stored, and the message **acked** with `XACK` so it isn't redelivered.
"""

def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            # … here you'd call a real email provider …
            r.set(f"jobresult:{f['job_id']}", 'sent')
            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

print('worker processed', run_worker(), 'job(s)')

"""## Step 5 — Tool functions (sync + async)

`check_inventory` and `create_order` are **synchronous** — they touch SQLite and return immediately.
`create_order` re-checks stock and decrements it in one transaction (guarding against overselling).
`send_confirmation` is **asynchronous** — it enqueues and returns a `job_id`. `check_job` polls a result.
"""

def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}
    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, round(price*qty, 2), 'created'))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': round(price*qty, 2)}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

# quick manual chain
inv = check_inventory('KB-01'); print(inv)
od  = create_order('KB-01', 2);  print(od)
jb  = send_confirmation('asha@x.com', od['order_id']); print(jb)
run_worker(); print(check_job(jb['job_id']))

"""## Step 6 — Tool schemas + dispatch"""

TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job}

def run_tool(name, args):
    fn = DISPATCH.get(name)
    if not fn: return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        return out, isinstance(out, dict) and 'error' in out
    except Exception as e:
        return {'error': repr(e)}, True
print('tools ready')

"""## Step 7 — The orchestrating agent loop

Same `stop_reason` loop as Colab 1, but now the model **chains** several tools in one turn and we
drain the worker afterwards. The offline mock scripts the full chain so the notebook runs without a key.
"""

import json
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order, '
  'then send_confirmation with the returned order_id. Report the order total and the email job status. '
  'If stock is insufficient, say so and do not create the order.'
)

def agent(user_text, max_steps=8, verbose=True):
    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        run_worker()
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}."

    from anthropic import Anthropic
    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            run_worker()  # drain any queued email jobs between steps
            continue
        return ''.join(b.text for b in resp.content if b.type=='text')
    return '(max steps reached)'

print(agent('Order one 4K monitor (SKU MON-4) and email asha@x.com the confirmation.'))

"""## Step 8 — Show the resulting state"""

print('Orders table:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)
print('Remaining stock:')
for row in db.execute('SELECT sku,qty FROM inventory').fetchall():
    print(' ', row)
# Try an out-of-stock order to see graceful failure
print('Out-of-stock attempt:', run_tool('create_order', {'sku':'HUB-2','qty':1}))

"""## Extension tasks

1. **Dead-letter & retry.** Make the worker fail jobs whose `to` is invalid; move them to an `emails:dlq`
   stream after N retries instead of acking. Add a tool to inspect the DLQ.
2. **Evaluator / verify step.** Add a `verify_order` tool that re-reads the order and confirms total &
   status; have the system prompt require it before declaring success (evaluator-optimiser pattern).
3. **Orchestrator-worker split.** Move `run_worker()` into a background `threading.Thread` loop so the
   agent never calls it directly; the queue truly decouples them.
4. **Human-in-the-loop gate.** For orders above a value threshold, have `create_order` return
   `{'status':'needs_approval'}` and require an `approve_order(order_id)` tool call before fulfilment.
5. **Trace spans.** Wrap `run_tool` to record `{tool, args, ms, ok}` per call; print a per-turn trace table.
6. **Prompt caching + token savings.** Mark the system prompt and tool block as cache-eligible and compare
   `usage.cache_read_input_tokens` across two identical turns; report the measured savings.

> **Stretch:** replace `fakeredis` with a real Redis (`redis.Redis.from_url(os.environ['REDIS_URL'])`) and
> run the worker as a genuinely separate Colab cell / process. The stream + consumer-group code is identical.
"""

!pip install -q numpy

"""---
# Capstone — Small Support Agent

**Extends Lab 2** into a full customer support agent with:
- **Redis short-term memory** — per-session conversation context
- **TinyVectorStore** — numpy cosine similarity for long-term knowledge recall (no external model)
- **7 tools** including 1 async queue-backed escalation tool
- **Routing + chaining** with a human-approval gate for high-value orders
- **Tracing** (per-tool timing), **retries** (exponential backoff), **prompt caching**
"""

# ── Capstone Step 1: Redis Short-Term Memory ──────────────────────────────
# Stores last N conversation turns per session in a Redis List.
# TTL = 5 min so stale sessions auto-expire.
import json, time

SESSION_TTL = 300  # seconds before an idle session expires

def session_key(session_id):
    return f"session:{session_id}"

def save_to_memory(session_id, role, content):
    """Push one message (role + content) to the session list."""
    key = session_key(session_id)
    r.rpush(key, json.dumps({"role": role, "content": content, "ts": time.time()}))
    r.expire(key, SESSION_TTL)   # refresh TTL on every write

def get_memory(session_id, last_n=6):
    """Retrieve the last N messages for this session."""
    raw = r.lrange(session_key(session_id), -last_n, -1)
    return [json.loads(m) for m in raw]

def clear_memory(session_id):
    r.delete(session_key(session_id))

def memory_to_messages(session_id):
    """Convert stored memory into the messages format Anthropic API expects."""
    return [{"role": m["role"], "content": m["content"]} for m in get_memory(session_id)]

# ── Smoke test ──
_sid = "demo_session"
save_to_memory(_sid, "user",      "I want to order a keyboard")
save_to_memory(_sid, "assistant", "Sure! KB-01 Mechanical Keyboard is $129. Shall I place the order?")
save_to_memory(_sid, "user",      "Yes please, 2 units")

mem = get_memory(_sid)
print(f"Session '{_sid}' has {len(mem)} message(s) in Redis short-term memory:")
for m in mem:
    print(f"  [{m['role']:>9}] {m['content']}")
clear_memory(_sid)
print("Memory cleared.")

# ── Capstone Step 2: TinyVectorStore — Long-Term Knowledge Recall ──────────
# Bag-of-words cosine similarity. No model download, no internet needed.
# Stores product info + policy docs; the agent queries it before answering.
import numpy as np

class TinyVectorStore:
    """Lightweight in-memory vector store using BoW cosine similarity."""
    def __init__(self):
        self.docs  = []
        self.vocab = {}

    def _embed(self, text):
        tokens = text.lower().split()
        for t in tokens:
            if t not in self.vocab:
                self.vocab[t] = len(self.vocab)
        vec = np.zeros(len(self.vocab))
        for t in tokens:
            if t in self.vocab:
                vec[self.vocab[t]] += 1
        n = np.linalg.norm(vec)
        return vec / n if n > 0 else vec

    def _pad(self, v):
        p = np.zeros(len(self.vocab))
        p[:len(v)] = v
        return p

    def add(self, doc_id, text, meta=None):
        self.docs.append({"id": doc_id, "text": text,
                          "meta": meta or {}, "vec": self._embed(text)})

    def query(self, query_text, n=2):
        qv = self._pad(self._embed(query_text))
        scored = [(float(np.dot(qv, self._pad(d["vec"]))), d) for d in self.docs]
        scored.sort(key=lambda x: -x[0])
        return [{"text": d["text"], "meta": d["meta"], "score": round(s, 3)}
                for s, d in scored[:n]]

# ── Seed the knowledge base ──
vs = TinyVectorStore()
KB_DOCS = [
    ("kb-1", "Mechanical keyboard KB-01 has 12 units in stock at price 129 dollars full N-key rollover RGB backlight",  {"sku": "KB-01", "type": "product"}),
    ("kb-2", "USB-C hub HUB-2 is currently out of stock price 58 dollars supports 7 ports USB",                         {"sku": "HUB-2", "type": "product"}),
    ("kb-3", "4K monitor MON-4 has 5 units at price 410 dollars 144Hz refresh rate HDR10 support",                      {"sku": "MON-4", "type": "product"}),
    ("kb-4", "Return policy items can be returned within 30 days with original packaging refund",                        {"type": "policy"}),
    ("kb-5", "Shipping policy free shipping on orders above 200 dollars standard delivery 3 to 5 days",                 {"type": "policy"}),
    ("kb-6", "Refund policy refunds processed within 7 business days to original payment method bank",                  {"type": "policy"}),
    ("kb-7", "Warranty policy all products carry 1 year manufacturer warranty replacement or repair",                   {"type": "policy"}),
]
for did, text, meta in KB_DOCS:
    vs.add(did, text, meta)

# ── Demo query ──
print("Knowledge base loaded:", len(vs.docs), "documents")
for q in ["4K monitor price stock", "refund return policy days"]:
    top = vs.query(q, n=1)[0]
    print(f"  Q: {q!r:40s}  →  [{top['score']:.2f}] {top['text'][:55]}…")

# ── Capstone Step 3: Tracing + Retry Infrastructure ───────────────────────
import functools, time

trace_log = []   # filled automatically as tools are called

def traced(fn):
    """Decorator: records tool name, kwargs, duration (ms), and success flag."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        t0 = time.perf_counter()
        try:
            out = fn(*args, **kwargs)
            ok  = not (isinstance(out, dict) and 'error' in out)
        except Exception as e:
            out = {'error': repr(e)}
            ok  = False
        ms = round((time.perf_counter() - t0) * 1000, 2)
        trace_log.append({"tool": fn.__name__, "args": kwargs, "ms": ms, "ok": ok})
        return out
    return wrapper

def with_retry(fn, max_retries=2, delay=0.1):
    """Wrap a function with exponential-backoff retry on error-dict responses."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        for attempt in range(max_retries + 1):
            res = fn(*args, **kwargs)
            if not (isinstance(res, dict) and 'error' in res):
                return res
            if attempt < max_retries:
                time.sleep(delay * (2 ** attempt))
        return res
    return wrapper

def print_trace_table():
    """Pretty-print the per-tool trace for the last agent turn."""
    if not trace_log:
        print("  (no traces yet)"); return
    print(f"\n  {'Tool':<26} {'Args':<34} {'ms':>6}  Status")
    print("  " + "─" * 74)
    for t in trace_log:
        status = "✓ OK" if t['ok'] else "✗ ERR"
        print(f"  {t['tool']:<26} {str(t['args'])[:32]:<34} {t['ms']:>6.1f}  {status}")

print("Tracing + retry utilities ready.")

# ── Capstone Step 4: Support Agent Tool Functions ─────────────────────────
#
# Tool inventory:
#   SYNC  1. search_knowledge_base  — vector search over KB
#   SYNC  2. create_support_ticket  — log a customer issue to SQLite
#   ASYNC 3. escalate_ticket        — Redis Stream → human review queue
#   SYNC  4. create_order           — place order; gate on $300 threshold
#   SYNC  5. approve_order          — human-in-the-loop gate approval
#   SYNC  6. send_confirmation      — enqueue confirmation email
#   SYNC  7. check_job              — poll email job status
#
APPROVAL_THRESHOLD = 300.0   # orders above this need human approval

# ── Create the tickets table (extends Lab 2's DB) ──
db.execute('''CREATE TABLE IF NOT EXISTS tickets
              (id INTEGER PRIMARY KEY AUTOINCREMENT,
               issue TEXT, email TEXT, status TEXT)''')
db.commit()

# ── Escalation stream ──
try:
    r.xgroup_create('escalations', 'human_agents', id='0', mkstream=True)
except Exception:
    pass

# ── 1. search_knowledge_base (SYNC) ──
@traced
def search_knowledge_base(query: str):
    """Semantic search over product info and policy documents."""
    results = vs.query(query, n=2)
    return {"results": [{"text": res["text"], "meta": res["meta"]} for res in results]}

# ── 2. create_support_ticket (SYNC) ──
@traced
def create_support_ticket(issue: str, email: str):
    """Log a customer complaint or request as a support ticket."""
    cur = db.execute(
        'INSERT INTO tickets (issue, email, status) VALUES (?, ?, ?)',
        (issue, email, 'open')
    )
    db.commit()
    return {"ticket_id": cur.lastrowid, "status": "open",
            "message": "Support ticket created successfully."}

# ── 3. escalate_ticket (ASYNC — Redis Stream) ──
@traced
def escalate_ticket(ticket_id: int, reason: str):
    """Push escalation onto Redis Stream for human review. Returns immediately."""
    jid = uuid.uuid4().hex[:8]
    r.xadd('escalations', {'job_id': jid, 'ticket_id': str(ticket_id), 'reason': reason})
    r.set(f'escalation:{jid}', 'queued')
    return {"job_id": jid, "ticket_id": ticket_id, "status": "queued",
            "message": "Escalation queued. A human agent will review shortly."}

# ── 4. create_order (SYNC, with human-approval gate) ──
@traced
def create_order(sku: str, qty: int):
    """Create an order. Returns needs_approval if total > APPROVAL_THRESHOLD."""
    row = db.execute(
        'SELECT qty, price FROM inventory WHERE sku=? LIMIT 1', (sku,)
    ).fetchone()
    if not row:
        return {'error': f'Unknown SKU: {sku}'}
    have, price = row
    if qty <= 0:
        return {'error': 'Quantity must be positive'}
    if have < qty:
        return {'error': f'Insufficient stock: have {have}, need {qty}'}
    total = round(price * qty, 2)
    if total > APPROVAL_THRESHOLD:
        cur = db.execute(
            'INSERT INTO orders (sku, qty, total, status) VALUES (?, ?, ?, ?)',
            (sku, qty, total, 'needs_approval')
        )
        db.commit()
        return {
            'order_id': cur.lastrowid, 'sku': sku, 'qty': qty,
            'total': total, 'status': 'needs_approval',
            'message': (f'Order total ${total} exceeds ${APPROVAL_THRESHOLD} threshold. '
                        f'Human approval required before fulfilment.')
        }
    db.execute('UPDATE inventory SET qty = qty - ? WHERE sku = ?', (qty, sku))
    cur = db.execute(
        'INSERT INTO orders (sku, qty, total, status) VALUES (?, ?, ?, ?)',
        (sku, qty, total, 'created')
    )
    db.commit()
    return {'order_id': cur.lastrowid, 'sku': sku, 'qty': qty,
            'total': total, 'status': 'created'}

# ── 5. approve_order (SYNC — human-in-the-loop gate) ──
@traced
def approve_order(order_id: int):
    """Approve a pending high-value order. Reserves inventory on approval."""
    row = db.execute(
        'SELECT status, sku, qty FROM orders WHERE id = ?', (order_id,)
    ).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    if row[0] != 'needs_approval':
        return {'error': f'Order {order_id} status is "{row[0]}", not needs_approval'}
    db.execute('UPDATE inventory SET qty = qty - ? WHERE sku = ?', (row[2], row[1]))
    db.execute("UPDATE orders SET status = 'created' WHERE id = ?", (order_id,))
    db.commit()
    return {'order_id': order_id, 'status': 'approved',
            'message': 'Order approved by human agent. Inventory reserved.'}

# ── 6. send_confirmation (SYNC, email via Redis queue) ──
@traced
def send_confirmation(to: str, order_id: int):
    """Enqueue confirmation email. Returns job_id immediately (non-blocking)."""
    jid = enqueue_email(to, f'Order #{order_id} Confirmed',
                        f'Hi! Your order #{order_id} has been confirmed and is being prepared.')
    return {'job_id': jid, 'status': 'queued'}

# ── 7. check_job (SYNC) ──
@traced
def check_job(job_id: str):
    """Check the status of a queued email job (queued / sent / unknown)."""
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

# ── Quick validation ──
print("=== Tool Validation ===")
print("KB search:   ", search_knowledge_base(query="keyboard stock")["results"][0]["text"][:55])
t = create_support_ticket(issue="Screen flickering on MON-4", email="bob@x.com")
print("Ticket:      ", t)
e = escalate_ticket(ticket_id=t["ticket_id"], reason="Hardware defect suspected")
print("Escalate:    ", e)
lo = create_order(sku="KB-01", qty=1)
hi = create_order(sku="MON-4", qty=1)
print("Low order:   ", lo)
print("High order:  ", hi)
print("Approve:     ", approve_order(order_id=hi["order_id"]))
cf = send_confirmation(to="bob@x.com", order_id=lo["order_id"])
run_worker()
print("Email job:   ", check_job(job_id=cf["job_id"]))

# ── Capstone Step 5: Tool Schemas + Prompt Caching Headers ───────────────
CAPSTONE_TOOLS = [
  {
    'name': 'search_knowledge_base',
    'description': (
        'Search product information, stock levels, pricing, and store policies '
        '(shipping, returns, refunds, warranty). Use this FIRST for any factual '
        'question before answering from memory.'
    ),
    'input_schema': {
        'type': 'object',
        'properties': {
            'query': {'type': 'string', 'description': 'Natural language search query.'}
        },
        'required': ['query']
    }
  },
  {
    'name': 'create_support_ticket',
    'description': 'Create a support ticket for a customer complaint, defect report, or service request.',
    'input_schema': {
        'type': 'object',
        'properties': {
            'issue': {'type': 'string', 'description': 'Description of the issue.'},
            'email': {'type': 'string', 'description': 'Customer email address.'}
        },
        'required': ['issue', 'email']
    }
  },
  {
    'name': 'escalate_ticket',
    'description': (
        'Escalate an urgent ticket for immediate human-agent review. '
        'Async — enqueues on Redis Stream and returns job_id immediately.'
    ),
    'input_schema': {
        'type': 'object',
        'properties': {
            'ticket_id': {'type': 'integer'},
            'reason':    {'type': 'string', 'description': 'Why this needs urgent human review.'}
        },
        'required': ['ticket_id', 'reason']
    }
  },
  {
    'name': 'create_order',
    'description': (
        'Place an order for a SKU. Returns status=created if total <= $300, '
        'or status=needs_approval if total > $300 (human gate required).'
    ),
    'input_schema': {
        'type': 'object',
        'properties': {
            'sku': {'type': 'string'},
            'qty': {'type': 'integer', 'description': 'Number of units to order (must be > 0).'}
        },
        'required': ['sku', 'qty']
    }
  },
  {
    'name': 'approve_order',
    'description': 'Approve a high-value order that is waiting for human authorisation.',
    'input_schema': {
        'type': 'object',
        'properties': {
            'order_id': {'type': 'integer'}
        },
        'required': ['order_id']
    }
  },
  {
    'name': 'send_confirmation',
    'description': 'Queue a confirmation email to the customer after a successful order.',
    'input_schema': {
        'type': 'object',
        'properties': {
            'to':       {'type': 'string', 'description': 'Customer email address.'},
            'order_id': {'type': 'integer'}
        },
        'required': ['to', 'order_id']
    }
  },
  {
    'name': 'check_job',
    'description': 'Check the delivery status of a queued email job (queued / sent / unknown).',
    'input_schema': {
        'type': 'object',
        'properties': {
            'job_id': {'type': 'string'}
        },
        'required': ['job_id']
    }
  },
]

# Add cache_control to last tool → Anthropic caches the entire tools block
CAPSTONE_TOOLS[-1]['cache_control'] = {'type': 'ephemeral'}

CAPSTONE_DISPATCH = {
    'search_knowledge_base': search_knowledge_base,
    'create_support_ticket': create_support_ticket,
    'escalate_ticket':       escalate_ticket,
    'create_order':          create_order,
    'approve_order':         approve_order,
    'send_confirmation':     send_confirmation,
    'check_job':             check_job,
}

def run_tool_cs(name, args):
    fn = CAPSTONE_DISPATCH.get(name)
    if not fn:
        return {'error': f'unknown tool: {name}'}, True
    out = fn(**args)
    return out, isinstance(out, dict) and 'error' in out

print("Capstone tools registered:", [t['name'] for t in CAPSTONE_TOOLS])

# ── Capstone Step 6: Full Support Agent Loop ──────────────────────────────
CAPSTONE_SYSTEM = [
    {
        "type": "text",
        "text": (
            "You are a helpful customer support agent for a tech accessories store.\n"
            "You help customers with product questions, placing orders, complaints, and policy queries.\n\n"
            "ROUTING RULES:\n"
            "1. Product / policy question  → call search_knowledge_base first, then answer.\n"
            "2. Place an order             → call create_order.\n"
            "   - If status=created        → call send_confirmation, then check_job.\n"
            "   - If status=needs_approval → inform customer, do NOT auto-approve.\n"
            "3. Customer complaint/defect  → create_support_ticket, then escalate_ticket if urgent.\n\n"
            "Always be concise. End each response with: order total (if applicable) "
            "and email job status (if applicable)."
        ),
        "cache_control": {"type": "ephemeral"}   # ← prompt caching
    }
]

def support_agent(user_text, session_id="default", max_steps=10, verbose=True):
    """
    Full orchestrating support agent.
    - Loads short-term memory for session context
    - Chains tools based on ROUTING RULES
    - Saves reply back to session memory
    - Prints trace table after each turn
    """
    trace_log.clear()

    # ── OFFLINE MOCK (no API key) ──
    if not LIVE:
        if verbose:
            print("  [mock] Running offline chain: search → order → approval gate → confirm")
        kb, _ = run_tool_cs('search_knowledge_base', {'query': 'MON-4 monitor stock price'})
        od, _ = run_tool_cs('create_order',          {'sku': 'MON-4', 'qty': 1})
        if od.get('status') == 'needs_approval':
            if verbose: print(f"  [mock] Order ${od['total']} > threshold → human approval gate triggered")
            ap, _ = run_tool_cs('approve_order', {'order_id': od['order_id']})
            if verbose: print(f"  [mock] Human approved order #{od['order_id']}")
        cf, _ = run_tool_cs('send_confirmation', {'to': 'customer@x.com', 'order_id': od['order_id']})
        run_worker()
        st, _ = run_tool_cs('check_job', {'job_id': cf['job_id']})
        save_to_memory(session_id, "user", user_text)
        reply = (
            f"(mock) KB found: {kb['results'][0]['text'][:50]}…\n"
            f"Order #{od['order_id']} — Total: ${od['total']} — "
            f"Status: approved. Confirmation email: {st['status']}."
        )
        save_to_memory(session_id, "assistant", reply)
        print_trace_table()
        return reply

    # ── LIVE MODE ──
    from anthropic import Anthropic
    A = Anthropic()

    history = memory_to_messages(session_id)
    history.append({"role": "user", "content": user_text})
    save_to_memory(session_id, "user", user_text)

    token_report = {}

    for step in range(max_steps):
        resp = A.messages.create(
            model=MODEL,
            max_tokens=1024,
            system=CAPSTONE_SYSTEM,
            tools=CAPSTONE_TOOLS,
            messages=history,
        )
        if hasattr(resp, 'usage'):
            token_report = {
                'input_tokens':          resp.usage.input_tokens,
                'cache_creation_tokens': getattr(resp.usage, 'cache_creation_input_tokens', 0),
                'cache_read_tokens':     getattr(resp.usage, 'cache_read_input_tokens', 0),
                'output_tokens':         resp.usage.output_tokens,
            }

        if resp.stop_reason == 'tool_use':
            history.append({"role": "assistant",
                             "content": [b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose:
                        print(f"  → {b.name}({b.input})")
                    out, is_err = run_tool_cs(b.name, b.input)
                    results.append({'type': 'tool_result', 'tool_use_id': b.id,
                                    'content': json.dumps(out), 'is_error': is_err})
            history.append({"role": "user", "content": results})
            run_worker()
            continue

        reply = ''.join(b.text for b in resp.content if b.type == 'text')
        save_to_memory(session_id, "assistant", reply)
        print_trace_table()
        if token_report:
            print(f"\n  Token report (prompt caching): {token_report}")
        return reply

    return '(max steps reached)'

print("Support agent ready.")

# ── Capstone Step 7: Run the Agent ────────────────────────────────────────

print("=" * 60)
print("TEST 1: Product question (triggers search_knowledge_base)")
print("=" * 60)
print(support_agent(
    "Do you have the 4K monitor in stock? What's the price?",
    session_id="sess_alice"
))

print()
print("=" * 60)
print("TEST 2: High-value order (triggers human-approval gate)")
print("=" * 60)
print(support_agent(
    "I'd like to order 1x MON-4 monitor. My email is alice@x.com",
    session_id="sess_alice"
))

print()
print("=" * 60)
print("TEST 3: Policy question")
print("=" * 60)
print(support_agent(
    "What is your refund policy?",
    session_id="sess_bob"
))

print()
print("=" * 60)
print("TEST 4: Complaint + escalation (async queue)")
print("=" * 60)
print(support_agent(
    "My keyboard arrived broken! Escalate this urgently. Email: carol@x.com",
    session_id="sess_carol"
))

# ── Capstone Step 8: Final State ──────────────────────────────────────────
print("── Orders ──────────────────────────────────────────────")
for row in db.execute('SELECT id, sku, qty, total, status FROM orders').fetchall():
    print(f"  Order #{row[0]}: {row[1]} x{row[2]}  ${row[3]}  [{row[4]}]")

print("\n── Tickets ─────────────────────────────────────────────")
for row in db.execute('SELECT id, issue, email, status FROM tickets').fetchall():
    print(f"  Ticket #{row[0]}: {row[2]}  '{row[1][:45]}'  [{row[3]}]")

print("\n── Remaining Inventory ──────────────────────────────────")
for row in db.execute('SELECT sku, name, qty FROM inventory').fetchall():
    print(f"  {row[0]}: {row[1]:<25} qty={row[2]}")

print("\n── Session Memory (last session) ────────────────────────")
for m in get_memory("sess_carol"):
    print(f"  [{m['role']:>9}] {m['content'][:65]}")



"""## Architecture Note

### Design Decisions

**Short-term memory (Redis List)**
Each session maps to a Redis List key (`session:<id>`). Messages are appended with `RPUSH` and retrieved with `LRANGE(-N, -1)`. A 5-minute TTL auto-expires idle sessions. `memory_to_messages()` reconstructs the Anthropic-format history before every agent call.

**Long-term recall (TinyVectorStore)**
A bag-of-words cosine similarity store seeded at startup with product facts and policy documents. No external model download — works fully offline in Colab. The agent calls `search_knowledge_base` first for any factual question, grounding answers in the KB rather than model training data.

**Sync vs. Async boundary**
`escalate_ticket` is the only async tool: it returns a `job_id` immediately after `XADD` to a Redis Stream (`escalations`). A consumer group (`human_agents`) provides at-least-once delivery and acknowledgement. The agent turn stays fast; the slow side-effect is off the critical path.

**Human-approval gate**
`create_order` checks `total > $300`. If true, the order is inserted with `status=needs_approval` (no inventory deducted yet). `approve_order` is the explicit unlock — it deducts inventory and flips the status. This prevents overselling and ensures human review of high-value transactions.

**Tracing**
The `@traced` decorator wraps every tool, recording `{tool, args, ms, ok}` into `trace_log`. `print_trace_table()` displays a per-turn latency + success table after each agent call.

**Retries**
`with_retry(fn, max_retries=2)` adds exponential backoff (0.1s → 0.2s) on transient `{error: ...}` responses.

**Prompt caching**
`cache_control: {type: ephemeral}` is set on both the system prompt block and the last tool schema. On repeated calls the API returns `cache_read_input_tokens` instead of billing full input tokens — visible in the token report printed after each live agent call.

**Routing**
The system prompt encodes three routing rules. Claude picks the right tool chain based on user intent — no hard-coded `if/else` needed in the orchestrator.
"""