# -*- coding: utf-8 -*-
"""Day_4_Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Km9J7BwPfhvb1CP43KuIX5ZF31PqJpbN
"""

# ============================================================
# CELL 1 : Setup Dataset and Broken Query
# ============================================================

import pandas as pd
import sqlite3

# Create SQLite connection
conn = sqlite3.connect(':memory:')

# ------------------------------------------------------------
# Server Inventory Table
# ------------------------------------------------------------

servers_inventory = {

    "Host_ID": [
        "SRV-01",
        "SRV-02",
        "SRV-03"
    ],

    "Role": [
        "Web Front",
        "API Gateway",
        "Database Replica"
    ]
}

# ------------------------------------------------------------
# Live Interfaces Table
# ------------------------------------------------------------

live_interfaces = {

    "Interface_ID": [
        "eth0",
        "eth1"
    ],

    "Mapped_Host": [
        "SRV-01",
        "SRV-02"
    ],

    "IP_Address": [
        "10.0.0.4",
        "10.0.0.9"
    ]
}

# ------------------------------------------------------------
# Create DataFrames
# ------------------------------------------------------------

df_srv = pd.DataFrame(servers_inventory)
df_inf = pd.DataFrame(live_interfaces)

# ------------------------------------------------------------
# Store Tables in SQLite
# ------------------------------------------------------------

df_srv.to_sql(
    'Servers',
    conn,
    index=False,
    if_exists='replace'
)

df_inf.to_sql(
    'Interfaces',
    conn,
    index=False,
    if_exists='replace'
)

# ------------------------------------------------------------
# Faulty INNER JOIN Query
# ------------------------------------------------------------

faulty_query = """
SELECT
    s.Host_ID,
    s.Role,
    i.Interface_ID,
    i.IP_Address

FROM Servers s

INNER JOIN Interfaces i
ON s.Host_ID = i.Mapped_Host
"""

print("--- Faulty Output Metrics (Missing Database Replica SRV-03) ---")

display(pd.read_sql_query(faulty_query, conn))

# ============================================================
# QUESTION 1 : Why is SRV-03 excluded?
# ============================================================

print("QUESTION 1 : Why is SRV-03 excluded?")

print("""
SRV-03 is excluded because INNER JOIN only returns
rows that have matching values in both tables.

SRV-03 exists in the Servers table,
but there is no matching record for SRV-03
inside the Interfaces table.

Since no interface is mapped to SRV-03,
INNER JOIN removes it from the final output.
""")

# ============================================================
# QUESTION 2 : Correct Query using LEFT JOIN
# ============================================================

correct_query = """
SELECT
    s.Host_ID,
    s.Role,
    i.Interface_ID,
    i.IP_Address

FROM Servers s

LEFT JOIN Interfaces i
ON s.Host_ID = i.Mapped_Host
"""

print("--- Correct Output Metrics (All Servers Included) ---")

display(pd.read_sql_query(correct_query, conn))

