# -*- coding: utf-8 -*-
"""Day_4_Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qF05mLiloWrPOmqcUEJ6cdT4cIPBGlpY
"""

# ============================================================
# CELL 4 : Second Normal Form (2NF) - Theory
# ============================================================

print("""
Rule for 2NF:

A table must already be in 1NF, and
no partial dependencies should exist.

Every non-prime attribute must depend
on the entire primary key,
not just part of it.
""")

# ============================================================
# CELL 5 : Third Normal Form (3NF) - Theory
# ============================================================

print("""
Third Normal Form (3NF)

Rule:
Must already be in 2NF, and
no transitive dependencies should exist.

Non-prime attributes must not depend
on other non-prime attributes.

Example:
Course_Code -> Instructor_ID
Instructor_ID -> Instructor_Name, Instructor_Office

Therefore:
Instructor_Office transitively depends
on Course_Code via Instructor_ID.
""")

# ============================================================
# CELL 6 : 3NF Implementation
# ============================================================

# Create Courses table from 1NF data
df_courses_2nf = df_1nf[
    [
        'Course_Code',
        'Course_Name',
        'Instructor_ID',
        'Instructor_Name',
        'Instructor_Office'
    ]
].drop_duplicates().reset_index(drop=True)

# ------------------------------------------------------------
# Extract Instructors into a separate table
# to eliminate transitive dependency
# ------------------------------------------------------------

df_instructors_3nf = df_courses_2nf[
    [
        'Instructor_ID',
        'Instructor_Name',
        'Instructor_Office'
    ]
].drop_duplicates().reset_index(drop=True)

# ------------------------------------------------------------
# Clean Courses table
# Keep only Instructor_ID as Foreign Key
# ------------------------------------------------------------

df_courses_3nf = df_courses_2nf[
    [
        'Course_Code',
        'Course_Name',
        'Instructor_ID'
    ]
].drop_duplicates().reset_index(drop=True)

# ------------------------------------------------------------
# Save to SQL
# ------------------------------------------------------------

df_instructors_3nf.to_sql(
    'Instructors_3NF',
    conn,
    index=False,
    if_exists='replace'
)

df_courses_3nf.to_sql(
    'Courses_3NF',
    conn,
    index=False,
    if_exists='replace'
)

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("--- 3NF Schema Refinement ---")

print("\n[Courses 3NF] (No transitive dependency)")
display(df_courses_3nf)

print("\n[Instructors 3NF] (New isolated table)")
display(df_instructors_3nf)

# ============================================================
# CELL 7 : Challenge Dataset Setup (0NF)
# ============================================================

# RUN THIS CELL TO SETUP THE CHALLENGE DATA

import pandas as pd
import sqlite3

conn_challenge = sqlite3.connect(':memory:')

challenge_data = {

    "Visit_ID": [5001, 5001, 5002, 5003],

    "Student_ID": [101, 101, 102, 104],

    "Student_Name": [
        "Alice",
        "Alice",
        "Bob",
        "David"
    ],

    "Doctor_ID": [
        "DOC_XYZ",
        "DOC_XYZ",
        "DOC_ABC",
        "DOC_XYZ"
    ],

    "Doctor_Name": [
        "Dr. Evans",
        "Dr. Evans",
        "Dr. Green",
        "Dr. Evans"
    ],

    "Doctor_Clinic": [
        "General Medicine",
        "General Medicine",
        "Sports Med",
        "General Medicine"
    ],

    "Prescriptions": [
        "Amoxicillin, Ibuprofen",
        "Amoxicillin, Ibuprofen",
        "Bandages",
        "Vitamin D"
    ]
}

# Create DataFrame
df_challenge = pd.DataFrame(challenge_data)

# Save to SQL
df_challenge.to_sql(
    'Patient_Visits_0NF',
    conn_challenge,
    index=False,
    if_exists='replace'
)

print("--- Challenge Dataset (0NF) ---")
display(df_challenge)

# ============================================================
# CELL 8 : Scenario Explanation
# ============================================================

print("""
The Scenario: Patient Medical Records

The university health center uses the following
table structure to track student medical visits,
prescriptions, and primary doctors.

Rules of the Health Center:

1. Each doctor belongs to exactly one
   primary department clinic
   (e.g., General Medicine, Sports Med).

2. A department clinic can have multiple doctors.

3. Multiple medications can be prescribed
   during a single visit.
""")

# ============================================================
# CELL 8 ANSWER : Convert Challenge Dataset to 1NF
# ============================================================

# Split prescriptions into atomic values
df_patient_1nf = df_challenge.assign(
    Prescriptions=df_challenge['Prescriptions'].str.split(',')
).explode('Prescriptions')

# Remove extra spaces
df_patient_1nf['Prescriptions'] = (
    df_patient_1nf['Prescriptions'].str.strip()
)

# Save to SQL
df_patient_1nf.to_sql(
    'Patient_Visits_1NF',
    conn_challenge,
    index=False,
    if_exists='replace'
)

print("--- Patient Visits in 1NF ---")
print(
    f"Row count increased from {len(df_challenge)} "
    f"to {len(df_patient_1nf)} due to flattening."
)

display(df_patient_1nf)

# ============================================================
# TASK 1 : Identify the Flaws
# ============================================================

print("TASK 1 : Identify the Flaws")

# ------------------------------------------------------------
# Q1
# ------------------------------------------------------------

print("\n1. Why does this table violate 1NF?")
print(
    "The table violates 1NF because the "
    "'Prescriptions' column contains multiple "
    "values in a single cell."
)

print("\nCulprit Column:")
print("Prescriptions")

# ------------------------------------------------------------
# Q2
# ------------------------------------------------------------

print(
    "\n2. Why do Student_Name and Doctor_Clinic "
    "violate 2NF and 3NF?"
)

print(
    "- Student_Name depends on Student_ID "
    "instead of the full primary key Visit_ID."
)

print(
    "- Doctor_Clinic depends on Doctor_ID "
    "instead of Visit_ID."
)

print(
    "- This creates partial and transitive dependencies."
)

# ------------------------------------------------------------
# Q3
# ------------------------------------------------------------

print("\n3. Which normal form is violated?")

print(
    "3NF is violated because "
    "Doctor_ID determines Doctor_Clinic, "
    "creating a transitive dependency."
)

# ============================================================
# TASK 2 : Fix with Code (Convert to 1NF)
# ============================================================

# Split multi-valued prescriptions into atomic values

df_task_1nf = df_challenge.assign(
    Prescriptions=df_challenge['Prescriptions'].str.split(',')
).explode('Prescriptions')

# Remove extra spaces
df_task_1nf['Prescriptions'] = (
    df_task_1nf['Prescriptions'].str.strip()
)

# Save normalized table to SQL
df_task_1nf.to_sql(
    'Patient_Visits_1NF',
    conn_challenge,
    index=False,
    if_exists='replace'
)

print("\n--- Patient Visits in 1NF ---")

print(
    f"Row count increased from "
    f"{len(df_challenge)} to {len(df_task_1nf)}"
)

# Display normalized dataframe
display(df_task_1nf)

