# -*- coding: utf-8 -*-
"""Researcher_Supervisor (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IS94T26UiVi0DLPM3F2LPqZNnUu9t7tV
"""

!pip install langchain-groq langchain-community langgraph tavily-python pydantic -q

import os
os.environ["GROQ_API_KEY"] = "gsk_YOUR_KEY_HERE"
os.environ["TAVILY_API_KEY"] = "tvly-YOUR_KEY_HERE"

import operator
from typing import Annotated, List, TypedDict, Literal
from pydantic import BaseModel, Field

# The State object that travels through the graph
class AgentState(TypedDict):
    task: str
    research_notes: Annotated[List[str], operator.add]
    draft: str
    next_node: str
    retry_count: int
    revision_feedback: str

# Schema for the Supervisor to follow
class Router(BaseModel):
    """Decide which worker to call next."""
    next_worker: Literal["researcher", "writer", "FINISH"] = Field(description="The next node to act")
    instructions: str = Field(description="Specific instructions for the worker")
    is_critical: bool = Field(description="If True, system will pause for human review")

from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults

# Using Llama 3.3 70B for the "Brain" (Supervisor)
llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0)
search_tool = TavilySearchResults(k=2)

def researcher(state: AgentState):
    print("🚀 Researcher is digging...")
    query = state['task']
    results = search_tool.invoke(query)
    print(results)
    return {"research_notes": [str(results)], "retry_count": 0}

def writer(state: AgentState):
    print("✍️ Writer is composing...")
    context = "\n".join(state['research_notes'])
    res = llm.invoke(f"Write a report on {state['task']} using: {context}")
    return {"draft": res.content}

def supervisor(state: AgentState):
    print("🧠 Supervisor is reviewing state...")
    # Groq supports structured output natively
    structured_llm = llm.with_structured_output(Router)

    prompt = f"""
    Task: {state['task']}
    Notes collected: {len(state['research_notes'])}
    Current Draft: {state['draft'][:100]}...
    If you have something in research_notes, select writer
    """
    print(f"Supervisor sees {len(state['research_notes'])} notes and draft length {len(state['draft'])}")
    decision = structured_llm.invoke(prompt)
    return {
        "next_node": decision.next_worker,
        "revision_feedback": decision.instructions
    }

# ✅ Correct way to use Colab Secrets
from google.colab import userdata
import os

os.environ["GROQ_API_KEY"]   = userdata.get('GROQ_API_KEY')
os.environ["TAVILY_API_KEY"] = userdata.get('TAVILY_API_KEY')

print("✅ Keys loaded successfully!")

import os

# ── Step 1: Check what key os.environ actually holds ──────────────────
key = os.environ.get("GROQ_API_KEY", "NOT SET")
print(f"Key in os.environ: '{key[:8]}...{key[-4:]}'" if len(key) > 12 else f"Key: '{key}'")

# ── Step 2: Check what key the llm object is actually using ───────────
print(f"Key inside llm object: '{str(llm.groq_api_key)[:8]}...{str(llm.groq_api_key)[-4:]}'")

# ── Step 3: Force re-create llm with the current key ──────────────────
from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults

llm          = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0)
search_tool  = TavilySearchResults(k=2)
print(f"New llm key:         '{str(llm.groq_api_key)[:8]}...{str(llm.groq_api_key)[-4:]}'")

# ── Step 4: Quick live test before touching the graph ─────────────────
try:
    test = llm.invoke("Say OK")
    print(f"✅ Groq API works! Response: {test.content}")
except Exception as e:
    print(f"❌ Still failing: {e}")

# Graph with recovery and breakpoints
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

builder = StateGraph(AgentState)

# Add nodes
builder.add_node("supervisor", supervisor)
builder.add_node("researcher", researcher)
builder.add_node("writer", writer)

# Logic
builder.set_entry_point("supervisor")

builder.add_conditional_edges(
    "supervisor",
    lambda x: x["next_node"],
    {"researcher": "researcher", "writer": "writer", "FINISH": END}
)

builder.add_edge("researcher", "supervisor")
builder.add_edge("writer", "supervisor")

# Enable Persistence (Recovery) and Breakpoints (Pause)
memory = MemorySaver()
graph = builder.compile(
    checkpointer=memory,
    interrupt_before=["writer"] # PAUSE: Allows human to review research before writing starts
)

config = {"configurable": {"thread_id": "workshop_user_1"}}
initial_input = {"task": "Impact of LPU architecture on AI inference speeds", "research_notes": [], "retry_count": 0, "draft": ""}

# 1. Start execution
print("--- STARTING GRAPH ---")
for event in graph.stream(initial_input, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")

# 2. Check if we hit a breakpoint (Pause)
snapshot = graph.get_state(config)
if snapshot.next:
    print(f"\n⏸️ SYSTEM PAUSED. Next step is: {snapshot.next}")
    print(f"Feedback from Supervisor: {snapshot.values['revision_feedback']}")

    # 3. Resume (Human says 'Go ahead')
    print("\n--- RESUMING AFTER PAUSE ---")
    #for event in graph.stream(None, config, stream_mode="values"):
    #    print("Finalizing...")

print("--- RESUMING GRAPH ---\n")
for event in graph.stream(None, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")
    elif "draft" in event:
        print(f"\n--- FINAL DRAFT ---:\n{event['draft']}")

# ═══════════════════════════════════════════════════════════════════
#  ARCHITECTURE VISUALIZER  — Tested & Corrected
# ═══════════════════════════════════════════════════════════════════
from IPython.display import Image, display, HTML

print("🎨 Rendering Multi-Agent Architecture...\n")

# ── Method 1: Mermaid.ink API (default, works in Colab) ─────────────
try:
    png_data = graph.get_graph(xray=True).draw_mermaid_png()
    display(Image(png_data))
    print("✅ Rendered via Mermaid.ink API")

# ── Method 2: Pyppeteer local render (if API is blocked) ────────────
except Exception as e1:
    print(f"⚠️  API failed ({e1})\n   Trying Pyppeteer local render...\n")
    try:
        import subprocess, sys
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "pyppeteer", "-q"], check=True
        )

        from langchain_core.runnables.graph_mermaid import MermaidDrawMethod

        png_data = graph.get_graph(xray=True).draw_mermaid_png(
            draw_method=MermaidDrawMethod.PYPPETEER
        )
        display(Image(png_data))
        print("✅ Rendered via Pyppeteer")

    # ── Method 3: HTML + Mermaid CDN (always works) ─────────────────
    except Exception as e2:
        print(f"⚠️  Pyppeteer failed too. Rendering as HTML...\n")

        mermaid_src = graph.get_graph().draw_mermaid()

        display(HTML(f"""
        <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
        <script>mermaid.initialize({{startOnLoad:true, theme:'dark'}});</script>
        <div style="background:#0d1117; padding:24px; border-radius:12px;
                    border:1px solid #30363d;">
            <p style="color:#58a6ff; font-family:monospace; margin:0 0 16px 0;">
                🤖 Multi-Agent Architecture — Supervisor / Researcher / Writer
            </p>
            <div class="mermaid">{mermaid_src}</div>
        </div>
        """))
        print("✅ Rendered via HTML CDN")

# ── Always: print raw Mermaid (paste at mermaid.live to edit) ───────
print("\n📋 Raw Mermaid source:")
print(graph.get_graph().draw_mermaid())

