# -*- coding: utf-8 -*-
"""gan_image_generation_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSflcMu4ex-14X5-dPpY8wkAYLUpCpGX
"""

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt

# Generator Block
class Generator(nn.Module):

    def __init__(self, z_dim):
        super().__init__()

        self.model = nn.Sequential(
            nn.ConvTranspose2d(z_dim, 256, 7, 1, 0),   # 1x1 -> 7x7
            nn.BatchNorm2d(256),
            nn.ReLU(),

            nn.ConvTranspose2d(256, 128, 4, 2, 1),     # 7x7 -> 14x14
            nn.BatchNorm2d(128),
            nn.ReLU(),

            nn.ConvTranspose2d(128, 1, 4, 2, 1),       # 14x14 -> 28x28
            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

# Discriminator Block
class Discriminator(nn.Module):

    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1),
            nn.LeakyReLU(0.2),

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),

            nn.Flatten(),

            nn.Linear(128 * 7 * 7, 1),

            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

# Hyperparameters
batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10

# Dataset loading

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

dataloader = DataLoader(
    dataset,
    batch_size=batch_size,
    shuffle=True
)

print("Dataset Loaded Successfully")

# Loss function
criterion = nn.BCELoss()

# Models
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)

# Optimizers
optimizer_g = optim.Adam(
    generator.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

optimizer_d = optim.Adam(
    discriminator.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

print("Models Initialized Successfully")

# Function to display generated images

def show_images(fake):

    img = fake.detach().cpu()[:16]

    grid = img.view(16, 28, 28)

    fig, axes = plt.subplots(4, 4, figsize=(5, 5))

    for i, ax in enumerate(axes.flatten()):
        ax.imshow(grid[i], cmap='gray')
        ax.axis('off')

    plt.show()

# Training Loop

for epoch in range(epochs):

    for real, _ in dataloader:

        real = real.to(device)

        batch_size = real.size(0)

        # Generate fake images
        noise = torch.randn(batch_size, z_dim, 1, 1).to(device)

        fake = generator(noise)

        # Labels
        real_labels = torch.ones(batch_size, 1).to(device) * 0.9
        fake_labels = torch.zeros(batch_size, 1).to(device)

        # -------------------------
        # Train Discriminator
        # -------------------------

        # Real loss
        D_real = discriminator(real)

        loss_real = criterion(D_real, real_labels)

        # Fake loss
        D_fake = discriminator(fake.detach())

        loss_fake = criterion(D_fake, fake_labels)

        # Total discriminator loss
        loss_D = loss_real + loss_fake

        optimizer_d.zero_grad()

        loss_D.backward()

        optimizer_d.step()

        # -------------------------
        # Train Generator
        # -------------------------

        output = discriminator(fake)

        g_loss = criterion(output, real_labels)

        optimizer_g.zero_grad()

        g_loss.backward()

        optimizer_g.step()

    # Show images after each epoch
    print(f"\nEpoch [{epoch+1}/{epochs}]")
    print(f"Discriminator Loss: {loss_D.item():.4f}")
    print(f"Generator Loss: {g_loss.item():.4f}")

    print("\nReal Images:")
    show_images(real)

    print("\nGenerated Images:")
    show_images(fake)

# Generate final fake images

noise = torch.randn(16, z_dim, 1, 1).to(device)

fake_images = generator(noise)

show_images(fake_images)

# Higher Resolution Generator (64x64)

class HighResGenerator(nn.Module):

    def __init__(self, z_dim):
        super().__init__()

        self.model = nn.Sequential(

            # Input: z_dim x 1 x 1

            nn.ConvTranspose2d(z_dim, 512, 4, 1, 0),
            nn.BatchNorm2d(512),
            nn.ReLU(True),

            # 4x4

            nn.ConvTranspose2d(512, 256, 4, 2, 1),
            nn.BatchNorm2d(256),
            nn.ReLU(True),

            # 8x8

            nn.ConvTranspose2d(256, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            # 16x16

            nn.ConvTranspose2d(128, 64, 4, 2, 1),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            # 32x32

            nn.ConvTranspose2d(64, 1, 4, 2, 1),

            # 64x64

            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

# Higher Resolution Discriminator (64x64)

class HighResDiscriminator(nn.Module):

    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(

            # 64x64

            nn.Conv2d(1, 64, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),

            # 32x32

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            # 16x16

            nn.Conv2d(128, 256, 4, 2, 1),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),

            # 8x8

            nn.Conv2d(256, 512, 4, 2, 1),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),

            # 4x4

            nn.Conv2d(512, 1, 4, 1, 0),

            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x).view(-1, 1)

# Transform dataset to 64x64

transform_highres = transforms.Compose([

    transforms.Resize(64),

    transforms.ToTensor(),

    transforms.Normalize((0.5,), (0.5,))
])

dataset_highres = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform_highres
)

dataloader_highres = DataLoader(
    dataset_highres,
    batch_size=batch_size,
    shuffle=True
)

print("64x64 Dataset Ready")

# Initialize high resolution GAN

highres_generator = HighResGenerator(z_dim).to(device)

highres_discriminator = HighResDiscriminator().to(device)

# Optimizers

optimizer_g_hr = optim.Adam(
    highres_generator.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

optimizer_d_hr = optim.Adam(
    highres_discriminator.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

print("High Resolution GAN Initialized")

# Display function for 64x64 images

def show_highres_images(fake):

    img = fake.detach().cpu()[:16]

    grid = img.view(16, 64, 64)

    fig, axes = plt.subplots(4, 4, figsize=(8, 8))

    for i, ax in enumerate(axes.flatten()):

        ax.imshow(grid[i], cmap='gray')

        ax.axis('off')

    plt.show()

# Training High Resolution GAN

highres_epochs = 5

for epoch in range(highres_epochs):

    for real, _ in dataloader_highres:

        real = real.to(device)

        batch_size = real.size(0)

        # Generate fake images

        noise = torch.randn(batch_size, z_dim, 1, 1).to(device)

        fake = highres_generator(noise)

        # Labels

        real_labels = torch.ones(batch_size, 1).to(device) * 0.9

        fake_labels = torch.zeros(batch_size, 1).to(device)

        # --------------------------
        # Train Discriminator
        # --------------------------

        D_real = highres_discriminator(real)

        loss_real = criterion(D_real, real_labels)

        D_fake = highres_discriminator(fake.detach())

        loss_fake = criterion(D_fake, fake_labels)

        loss_D = loss_real + loss_fake

        optimizer_d_hr.zero_grad()

        loss_D.backward()

        optimizer_d_hr.step()

        # --------------------------
        # Train Generator
        # --------------------------

        output = highres_discriminator(fake)

        g_loss = criterion(output, real_labels)

        optimizer_g_hr.zero_grad()

        g_loss.backward()

        optimizer_g_hr.step()

    print(f"\nEpoch [{epoch+1}/{highres_epochs}]")

    print(f"Discriminator Loss: {loss_D.item():.4f}")

    print(f"Generator Loss: {g_loss.item():.4f}")

    show_highres_images(fake)

# Generate final high resolution images

noise = torch.randn(16, z_dim, 1, 1).to(device)

highres_fake_images = highres_generator(noise)

show_highres_images(highres_fake_images)