# -*- coding: utf-8 -*-
"""Synthetic Fraud Training Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zT4zPS2Vi6HBAtZgo-EEavtwbi9Xttk_
"""

print("=" * 80)
print("      GENAI BUSINESS CASE STUDY - NEXABANK")
print("=" * 80)

print("\nSelected Use Case : Synthetic Fraud Training Data")
print("Technology Used   : GAN (Generative Adversarial Network)")

intro = """
INTRODUCTION

Banks use machine learning models to detect fraud transactions.
These models require a large amount of labelled fraud data for training.

However, fraud data is limited and contains sensitive customer information.
Due to privacy laws like GDPR, banks cannot freely use real customer data.

To solve this problem, NexaBank can use Generative AI models such as GANs
to create synthetic fraud transaction data that looks realistic without
exposing actual customer information.
"""

print(intro)

import pandas as pd

print("=" * 80)
print("BUSINESS PROBLEM")
print("=" * 80)

problem = {
    "Area": ["Fraud Detection"],

    "Current Issue": [
        "Not enough labelled fraud samples available"
    ],

    "Business Impact": [
        "Weak fraud detection model performance"
    ],

    "Main Challenge": [
        "Cannot use real customer transaction data due to GDPR"
    ]
}

df_problem = pd.DataFrame(problem)

display(df_problem)

text = """
WHY THIS PROBLEM IS IMPORTANT

Fraud detection systems are extremely important in banking.
If the machine learning model is trained on limited data,
it may fail to detect new fraud patterns.

This can lead to:
1. Financial loss
2. Customer trust issues
3. Security risks
4. Compliance problems

Therefore, generating high-quality synthetic fraud data
can improve fraud detection systems significantly.
"""

print(text)

print("=" * 80)
print("PROPOSED GENAI SOLUTION")
print("=" * 80)

solution = {
    "Component": [
        "GenAI Type",
        "Recommended Model",
        "Alternative Model",
        "Purpose"
    ],

    "Details": [
        "Generative AI",
        "GAN (Generative Adversarial Network)",
        "CTGAN / Tabular GAN",
        "Generate realistic synthetic fraud samples"
    ]
}

df_solution = pd.DataFrame(solution)

display(df_solution)

gan_text = """
WHY GAN IS USED

GAN stands for Generative Adversarial Network.

GAN contains two neural networks:
1. Generator
2. Discriminator

The Generator creates fake fraud transaction samples.
The Discriminator checks whether the data is real or fake.

Through continuous training, GAN learns to generate
high-quality synthetic fraud transaction data that can
be used for machine learning model training.
"""

print(gan_text)

print("=" * 80)
print("DATA REQUIREMENTS")
print("=" * 80)

requirements = {
    "Required Data": [
        "Historical fraud patterns",
        "Fraud transaction labels",
        "Transaction metadata",
        "Anonymized datasets",
        "Balanced fraud samples"
    ],

    "Reason": [
        "Understand fraud behaviour",
        "Train supervised models",
        "Detect suspicious activities",
        "Protect customer privacy",
        "Reduce model bias"
    ]
}

df_requirements = pd.DataFrame(requirements)

display(df_requirements)

print("=" * 80)
print("BUSINESS VALUE AND ROI")
print("=" * 80)

roi = {
    "Expected Benefit": [
        "Better fraud detection accuracy",
        "Reduced dependency on real customer data",
        "Faster ML model training",
        "Improved privacy protection",
        "Scalable AI training pipeline"
    ],

    "Estimated Impact": [
        "20% improvement",
        "80% less sensitive data exposure",
        "30% faster processing",
        "GDPR compliant solution",
        "Supports future fraud analysis"
    ]
}

df_roi = pd.DataFrame(roi)

display(df_roi)

print("=" * 80)
print("RISK REGISTER")
print("=" * 80)

risk = {
    "Risk": [
        "Data Bias",
        "Privacy Leakage",
        "Poor Quality Synthetic Data",
        "Overfitting",
        "Regulatory Compliance"
    ],

    "Possible Impact": [
        "Incorrect predictions",
        "Sensitive data exposure",
        "Weak fraud detection",
        "Poor generalization",
        "Legal issues"
    ],

    "Mitigation": [
        "Use balanced datasets",
        "Apply anonymization",
        "Human quality validation",
        "Regular retraining",
        "Follow GDPR policies"
    ]
}

df_risk = pd.DataFrame(risk)

display(df_risk)

print("=" * 80)
print("SUCCESS METRICS")
print("=" * 80)

metrics = {
    "KPI": [
        "Fraud detection accuracy",
        "Synthetic data quality score",
        "Reduction in manual effort",
        "Training speed improvement",
        "Privacy compliance score"
    ],

    "Target": [
        ">= 92%",
        "90% similarity to real patterns",
        "30% reduction",
        "25% faster",
        "100% GDPR compliant"
    ]
}

df_metrics = pd.DataFrame(metrics)

display(df_metrics)

conclusion = """
FINAL CONCLUSION

NexaBank can use GAN-based Generative AI models to solve
the shortage of fraud training data while maintaining
customer privacy and regulatory compliance.

This solution helps improve fraud detection accuracy,
reduces dependency on sensitive customer information,
and supports scalable AI-based banking security systems.

The proposed business case provides both technical and
business benefits for future fraud detection systems.
"""

print(conclusion)

print("=" * 80)
print("SUBMITTED BY")
print("=" * 80)

print("Name    : Akash Chaurasiya")
print("Project : GenAI Business Case Study")
print("Topic   : Synthetic Fraud Training Data using GANs")

